<script>
import { t } from "$lib/Translations/index.js"
import Banner from "$lib/components/Banner.svelte"

import Fuse from "fuse.js"

let printbibles = [
	{
		link: "http://amzn.to/2xjwDSo",
		cover: "https://images.bible.cloud/covers/110x170/AAKWBT.jpg",
		name: "Ankave 1990 Edition",
		bid: "AAKWBT",
	},
	{
		link: "http://amzn.to/2xjsspQ",
		cover: "https://images.bible.cloud/covers/110x170/AAUWBT.jpg",
		name: "The New Testament in Abau",
		bid: "AAUWBT",
	},
	{
		link: "http://amzn.to/2gWpbWh",
		cover: "https://images.bible.cloud/covers/110x170/ABTWBT.jpg",
		name: "Maprik Ambulas New Testament",
		bid: "ABTWBT",
	},
	{
		link: "http://amzn.to/2xMmhe1",
		cover: "https://images.bible.cloud/covers/110x170/ABXWBT.jpg",
		name: "The New Testament in Inabaknon",
		bid: "ABXWBT",
	},
	{
		link: "http://amzn.to/2gYZdxF",
		cover: "https://images.bible.cloud/covers/110x170/ABYWBT.jpg",
		name: "The New Testament in Aneme Wake",
		bid: "ABYWBT",
	},
	{
		link: "http://amzn.to/2wVWzlK",
		cover: "https://images.bible.cloud/covers/110x170/ACCIBS.jpg",
		name: "1992 Edition",
		bid: "ACCIBS",
	},
	{
		link: "http://amzn.to/2jiXI1S",
		cover: "https://images.bible.cloud/covers/110x170/ACRNNT.jpg",
		name: "2009 Edition (New Alphabet)",
		bid: "ACRNNT",
	},
	{
		link: "http://amzn.to/2wVSHkt",
		cover: "https://images.bible.cloud/covers/110x170/ACRTNT.jpg",
		name: "2009 Edition (Traditional)",
		bid: "ACRTNT",
	},
	{
		link: "http://amzn.to/2w25H9A",
		cover: "https://images.bible.cloud/covers/110x170/ACUTBL.jpg",
		name: "Achuar-Shiwiar 1994 Edition",
		bid: "ACUTBL",
	},
	{
		link: "https://amzn.to/2KpIq7Y",
		cover: "https://images.bible.cloud/covers/110x170/AGDWBT.jpg",
		name: "The New Testament in Agarabi",
		bid: "AGDWBT",
	},
	{
		link: "http://amzn.to/2wkVwbj",
		cover: "https://images.bible.cloud/covers/110x170/AGGPNG.jpg",
		name: "Angor 2001 Edition",
		bid: "AGGPNG",
	},
	{
		link: "http://amzn.to/2gWSacJ",
		cover: "https://images.bible.cloud/covers/110x170/AGMWBT.jpg",
		name: "Angaataha 2004 Edition",
		bid: "AGMWBT",
	},
	{
		link: "http://amzn.to/2gXvnxt",
		cover: "https://images.bible.cloud/covers/110x170/AGNWPS.jpg",
		name: "The New Agreement Agutaynen Bible",
		bid: "AGNWPS",
	},
	{
		link: "https://amzn.to/2KmwKCR",
		cover: "https://images.bible.cloud/covers/110x170/AGRTBL.jpg",
		name: "Aguaruna 2005 Edition",
		bid: "AGRTBL",
	},
	{
		link: "https://amzn.to/2yJtVHg",
		cover: "https://images.bible.cloud/covers/110x170/AKEBSS.jpg",
		name: "Akawaio 2010 Edition",
		bid: "AKEBSS",
	},
	{
		link: "http://amzn.to/2xsjRAX",
		cover: "https://images.bible.cloud/covers/110x170/AKHBSP.jpg",
		name: "Angal Heneng 1978 Edition",
		bid: "AKHBSP",
	},
	{
		link: "http://amzn.to/2jj7H7f",
		cover: "https://images.bible.cloud/covers/110x170/AMETBL.jpg",
		name: "Yanesha' 2014 Edition",
		bid: "AMETBL",
	},
	{
		link: "http://amzn.to/2wkPVlx",
		cover: "https://images.bible.cloud/covers/110x170/AMMWBT.jpg",
		name: "The New Testament in Ama",
		bid: "AMMWBT",
	},
	{
		link: "http://amzn.to/2gWsAEM",
		cover: "https://images.bible.cloud/covers/110x170/AMNNAI.jpg",
		name: "Naineri Amanab New Testament",
		bid: "AMNNAI",
	},
	{
		link: "http://amzn.to/2jjIQjF",
		cover: "https://images.bible.cloud/covers/110x170/AMNWBT.jpg",
		name: "The New Testament in Amanab",
		bid: "AMNWBT",
	},
	{
		link: "http://amzn.to/2eRxVZE",
		cover: "https://images.bible.cloud/covers/110x170/AMPWBT.jpg",
		name: "The New Testament in Alamblak",
		bid: "AMPWBT",
	},
	{
		link: "http://amzn.to/2jCb7Cc",
		cover: "https://images.bible.cloud/covers/110x170/AMRWBT.jpg",
		name: "The New Testament in Amarakaeri",
		bid: "AMRWBT",
	},
	{
		link: "http://amzn.to/2xrOTcq",
		cover: "https://images.bible.cloud/covers/110x170/AMULLB.jpg",
		name: "Amuzgo de Guerrero New Testament",
		bid: "AMULLB",
	},
	{
		link: "http://amzn.to/2hdb3Vi",
		cover: "https://images.bible.cloud/covers/110x170/ANVWBT.jpg",
		name: "Denya 2010 Edition",
		bid: "ANVWBT",
	},
	{
		link: "https://amzn.to/2N22RGs",
		cover: "https://images.bible.cloud/covers/110x170/AOJFIL.jpg",
		name: "Mufian 1998 Edition",
		bid: "AOJFIL",
	},
	{
		link: "http://amzn.to/2wltI6J",
		cover: "https://images.bible.cloud/covers/110x170/AOJWBT.jpg",
		name: "Mufian 1998 Edition",
		bid: "AOJWBT",
	},
	{
		link: "http://amzn.to/2jjEskL",
		cover: "https://images.bible.cloud/covers/110x170/AOMWBT.jpg",
		name: "Ömie 1991 Edition",
		bid: "AOMWBT",
	},
	{
		link: "https://amzn.to/2N2jUbh",
		cover: "https://images.bible.cloud/covers/110x170/AONTBL.jpg",
		name: "Bumbita Arapesh 2003 Edition",
		bid: "AONTBL",
	},
	{
		link: "https://amzn.to/2yJq0Ky",
		cover: "https://images.bible.cloud/covers/110x170/APEAMA.jpg",
		name: "The New Testament in Mountain Arapesh",
		bid: "APEAMA",
	},
	{
		link: "https://amzn.to/2tGyzQL",
		cover: "https://images.bible.cloud/covers/110x170/APETBL.jpg",
		name: "Mountain Arapesh New Testament",
		bid: "APETBL",
	},
	{
		link: "http://amzn.to/2jiP1Ve",
		cover: "https://images.bible.cloud/covers/110x170/APRWBT.jpg",
		name: "The New Testament in the Arop dialect of the Arop-Lokep language",
		bid: "APRWBT",
	},
	{
		link: "https://amzn.to/2yGWrtm",
		cover: "https://images.bible.cloud/covers/110x170/APUTSA.jpg",
		name: "The New Testament in Apurina",
		bid: "APUTSA",
	},
	{
		link: "http://amzn.to/2f177tM",
		cover: "https://images.bible.cloud/covers/110x170/APWWNT.jpg",
		name: "Western Apache New Testament",
		bid: "APWWNT",
	},
	{
		link: "https://amzn.to/2yJCEcv",
		cover: "https://images.bible.cloud/covers/110x170/APYWBT.jpg",
		name: "The New Testament in Apalai",
		bid: "APYWBT",
	},
	{
		link: "https://amzn.to/2N1At7t",
		cover: "https://images.bible.cloud/covers/110x170/APZWBT.jpg",
		name: "Safeyoka 1988 Edition",
		bid: "APZWBT",
	},
	{
		link: "http://amzn.to/2gYbSku",
		cover: "https://images.bible.cloud/covers/110x170/ARLWBT.jpg",
		name: "The New Testament in Arabela",
		bid: "ARLWBT",
	},
	{
		link: "http://amzn.to/2wT7RYS",
		cover: "https://images.bible.cloud/covers/110x170/ARNSBU.jpg",
		name: "Mapudungun UBS Edition",
		bid: "ARNSBU",
	},
	{
		link: "https://amzn.to/2It89XO",
		cover: "https://images.bible.cloud/covers/110x170/ASOTBL.jpg",
		name: "Dano 1989 Edition",
		bid: "ASOTBL",
	},
	{
		link: "https://amzn.to/2N0U1bP",
		cover: "https://images.bible.cloud/covers/110x170/ATAPNG.jpg",
		name: "Pele-Ata 2009 Edition",
		bid: "ATAPNG",
	},
	{
		link: "https://amzn.to/2N0HPYL",
		cover: "https://images.bible.cloud/covers/110x170/ATBWBT.jpg",
		name: "New Testament in Zaiwa",
		bid: "ATBWBT",
	},
	{
		link: "http://amzn.to/2eRhYCI",
		cover: "https://images.bible.cloud/covers/110x170/ATDWBT.jpg",
		name: "New Testament in Manobo, Ata",
		bid: "ATDWBT",
	},
	{
		link: "http://amzn.to/2wSDQbp",
		cover: "https://images.bible.cloud/covers/110x170/ATGWYI.jpg",
		name: "Ivbie North-Okpela-Arhe 2012 Edition",
		bid: "ATGWYI",
	},
	{
		link: "http://amzn.to/2wC3a1f",
		cover: "https://images.bible.cloud/covers/110x170/ATTANT.jpg",
		name: "The New Testament in Atta, Pamplona",
		bid: "ATTANT",
	},
	{
		link: "http://amzn.to/2xsnerT",
		cover: "https://images.bible.cloud/covers/110x170/AUCWBT.jpg",
		name: "The New Testament in Waorani",
		bid: "AUCWBT",
	},
	{
		link: "http://amzn.to/2gZtLja",
		cover: "https://images.bible.cloud/covers/110x170/AUYWBT.jpg",
		name: "The New Testament in Awiyaana",
		bid: "AUYWBT",
	},
	{
		link: "http://amzn.to/2jjIJ7N",
		cover: "https://images.bible.cloud/covers/110x170/AVTWBT.jpg",
		name: "Au 1992 Edition",
		bid: "AVTWBT",
	},
	{
		link: "http://amzn.to/2eRBqzg",
		cover: "https://images.bible.cloud/covers/110x170/AWBTBL.jpg",
		name: "Awa 2002 Edition",
		bid: "AWBTBL",
	},
	{
		link: "http://amzn.to/2wTgYsl",
		cover: "https://images.bible.cloud/covers/110x170/AWXWBT.jpg",
		name: "Genesis, Ruth, and Jonah in Awara",
		bid: "AWXWBT",
	},
	{
		link: "http://amzn.to/2eRIRpX",
		cover: "https://images.bible.cloud/covers/110x170/AZGTBL.jpg",
		name: "San Pedro Amuzgos Amuzgo 1992 Edition",
		bid: "AZGTBL",
	},
	{
		link: "http://amzn.to/2fvay8K",
		cover: "https://images.bible.cloud/covers/110x170/AZZTBL.jpg",
		name: "Highland Puebla Nahuatl 1979 Edition",
		bid: "AZZTBL",
	},
	{
		link: "http://amzn.to/2wl0e9h",
		cover: "https://images.bible.cloud/covers/110x170/BAON10.jpg",
		name: "Waimaha 2010 Edition",
		bid: "BAON10",
	},
	{
		link: "http://amzn.to/2eZWozK",
		cover: "https://images.bible.cloud/covers/110x170/BBRWBT.jpg",
		name: "Girawa 1994 Edition",
		bid: "BBRWBT",
	},
	{
		link: "http://amzn.to/2wlhhYv",
		cover: "https://images.bible.cloud/covers/110x170/BDDPNG.jpg",
		name: "Bunama 1991 Edition",
		bid: "BDDPNG",
	},
	{
		link: "http://amzn.to/2wVzEH4",
		cover: "https://images.bible.cloud/covers/110x170/BEFWBT.jpg",
		name: "Benabena 1982 Edition",
		bid: "BEFWBT",
	},
	{
		link: "http://amzn.to/2fv7eur",
		cover: "https://images.bible.cloud/covers/110x170/BGSWBT.jpg",
		name: "The New Testament in Tagabawa",
		bid: "BGSWBT",
	},
	{
		link: "http://amzn.to/2eRyeUc",
		cover: "https://images.bible.cloud/covers/110x170/BHGBHG.jpg",
		name: "Portions in Binandere",
		bid: "BHGBHG",
	},
	{
		link: "http://amzn.to/2y9URuT",
		cover: "https://images.bible.cloud/covers/110x170/BIGWBT.jpg",
		name: "Biangai 2013 Edition",
		bid: "BIGWBT",
	},
	{
		link: "https://amzn.to/2Kfi6hG",
		cover: "https://images.bible.cloud/covers/110x170/BJRWBT.jpg",
		name: "Binumarien 1983 Edition",
		bid: "BJRWBT",
	},
	{
		link: "http://amzn.to/2gVZ55Y",
		cover: "https://images.bible.cloud/covers/110x170/BJVWYI.jpg",
		name: "Bedjond 2011 Edition",
		bid: "BJVWYI",
	},
	{
		link: "http://amzn.to/2xscFVD",
		cover: "https://images.bible.cloud/covers/110x170/BKDWBT.jpg",
		name: "The New Testament in Binukid",
		bid: "BKDWBT",
	},
	{
		link: "http://amzn.to/2wT3Bsd",
		cover: "https://images.bible.cloud/covers/110x170/BKQWBT.jpg",
		name: "The New Testament in Bakairi",
		bid: "BKQWBT",
	},
	{
		link: "https://amzn.to/2tw1Azp",
		cover: "https://images.bible.cloud/covers/110x170/BKXWBT.jpg",
		name: "Baikeno Gospel of Mark",
		bid: "BKXWBT",
	},
	{
		link: "https://amzn.to/2MXPPtr",
		cover: "https://images.bible.cloud/covers/110x170/BLWWBT.jpg",
		name: "The New Testament in Balangao",
		bid: "BLWWBT",
	},
	{
		link: "http://amzn.to/2wWgKA8",
		cover: "https://images.bible.cloud/covers/110x170/BLZLAI.jpg",
		name: "Formal Balantak version, 2010",
		bid: "BLZLAI",
	},
	{
		link: "http://amzn.to/2jkIauK",
		cover: "https://images.bible.cloud/covers/110x170/BMHWBT.jpg",
		name: "Kein 2005 Edition",
		bid: "BMHWBT",
	},
	{
		link: "http://amzn.to/2xswOLd",
		cover: "https://images.bible.cloud/covers/110x170/BMKWBT.jpg",
		name: "Ghayavi 2010 Edition",
		bid: "BMKWBT",
	},
	{
		link: "http://amzn.to/2gWXE7d",
		cover: "https://images.bible.cloud/covers/110x170/BMRWBT.jpg",
		name: "Muinane 2009 Edition",
		bid: "BMRWBT",
	},
	{
		link: "https://amzn.to/2N238sY",
		cover: "https://images.bible.cloud/covers/110x170/BMUPNG.jpg",
		name: "Somba-Siawari New Testament and Portions",
		bid: "BMUPNG",
	},
	{
		link: "https://amzn.to/2Iue3bz",
		cover: "https://images.bible.cloud/covers/110x170/BNPWBT.jpg",
		name: "The Scriptures in Bola",
		bid: "BNPWBT",
	},
	{
		link: "http://amzn.to/2wWiFoj",
		cover: "https://images.bible.cloud/covers/110x170/BOATBL.jpg",
		name: "The Scriptures in Bora",
		bid: "BOATBL",
	},
	{
		link: "http://amzn.to/2wSBlpA",
		cover: "https://images.bible.cloud/covers/110x170/BOJWBT.jpg",
		name: "Anjam New Testament, 2014 revision",
		bid: "BOJWBT",
	},
	{
		link: "https://amzn.to/2lBR2Ko",
		cover: "https://images.bible.cloud/covers/110x170/BOJYAA.jpg",
		name: "The New Testament in Anjam",
		bid: "BOJYAA",
	},
	{
		link: "https://amzn.to/2lBElj5",
		cover: "https://images.bible.cloud/covers/110x170/BONPNG.jpg",
		name: "Bine 1993 Edition",
		bid: "BONPNG",
	},
	{
		link: "https://amzn.to/2Itnc3W",
		cover: "https://images.bible.cloud/covers/110x170/BOXWYI.jpg",
		name: "Buamu 2012 Edition",
		bid: "BOXWYI",
	},
	{
		link: "http://amzn.to/2gZwigD",
		cover: "https://images.bible.cloud/covers/110x170/BPRWYI.jpg",
		name: "Koronadal Blaan 1995 Edition",
		bid: "BPRWYI",
	},
	{
		link: "https://amzn.to/2tCGMGz",
		cover: "https://images.bible.cloud/covers/110x170/BREBRB.jpg",
		name: "The Breton Bible",
		bid: "BREBRB",
	},
	{
		link: "http://amzn.to/2gYXHfb",
		cover: "https://images.bible.cloud/covers/110x170/BSNTBL.jpg",
		name: "Barasana-Eduria 2001 Edition",
		bid: "BSNTBL",
	},
	{
		link: "https://amzn.to/2ItoxYw",
		cover: "https://images.bible.cloud/covers/110x170/BSPPBT.jpg",
		name: "God's Holy Book",
		bid: "BSPPBT",
	},
	{
		link: "http://amzn.to/2y9SgRm",
		cover: "https://images.bible.cloud/covers/110x170/BSSWBT.jpg",
		name: "Akoose 2011 Edition",
		bid: "BSSWBT",
	},
	{
		link: "https://amzn.to/2tMjY6v",
		cover: "https://images.bible.cloud/covers/110x170/BUSSIM.jpg",
		name: "Bokobaru 2005 Edition",
		bid: "BUSSIM",
	},
	{
		link: "http://amzn.to/2wl1wkl",
		cover: "https://images.bible.cloud/covers/110x170/BYRWBT.jpg",
		name: "Baruya 1994 Edition",
		bid: "BYRWBT",
	},
	{
		link: "https://amzn.to/2lyu5rH",
		cover: "https://images.bible.cloud/covers/110x170/BZDWBT.jpg",
		name: "Common Language (Popular Version)",
		bid: "BZDWBT",
	},
	{
		link: "https://amzn.to/2IuzokP",
		cover: "https://images.bible.cloud/covers/110x170/BZHPNG.jpg",
		name: "Buang (Mapos) New Testament 2003",
		bid: "BZHPNG",
	},
	{
		link: "http://amzn.to/2xrVy6q",
		cover: "https://images.bible.cloud/covers/110x170/BZJBSW.jpg",
		name: "Belize Kriol English 2012 Edition",
		bid: "BZJBSW",
	},
	{
		link: "https://amzn.to/2yMDlSo",
		cover: "https://images.bible.cloud/covers/110x170/CAAWBT.jpg",
		name: "Ch'orti'­ 1996 Edition",
		bid: "CAAWBT",
	},
	{
		link: "http://amzn.to/2xsjN4m",
		cover: "https://images.bible.cloud/covers/110x170/CABNVS.jpg",
		name: "Garifuna 2002 Edition",
		bid: "CABNVS",
	},
	{
		link: "http://amzn.to/2gXKabk",
		cover: "https://images.bible.cloud/covers/110x170/CAFWBT.jpg",
		name: "The Bible in Southern Carrier",
		bid: "CAFWBT",
	},
	{
		link: "https://amzn.to/2N3X57k",
		cover: "https://images.bible.cloud/covers/110x170/CAKEAS.jpg",
		name: "Cakchiquel, Eastern 2012 Edition",
		bid: "CAKEAS",
	},
	{
		link: "http://amzn.to/2xsNG4q",
		cover: "https://images.bible.cloud/covers/110x170/CAKSBG.jpg",
		name: "Cakchiquel, Central 2003 Edition",
		bid: "CAKSBG",
	},
	{
		link: "http://amzn.to/2hd8OkQ",
		cover: "https://images.bible.cloud/covers/110x170/CAKSDS.jpg",
		name: "The Bible in Kaqchikel",
		bid: "CAKSDS",
	},
	{
		link: "http://amzn.to/2xhtod7",
		cover: "https://images.bible.cloud/covers/110x170/CAKSMJ.jpg",
		name: "Cakchiquel, Santa Maria de Jesus 2006 Edition",
		bid: "CAKSMJ",
	},
	{
		link: "http://amzn.to/2f1Aegh",
		cover: "https://images.bible.cloud/covers/110x170/CAKSOU.jpg",
		name: "Cakchiquel South Central 2007 Edition",
		bid: "CAKSOU",
	},
	{
		link: "http://amzn.to/2y9KR4J",
		cover: "https://images.bible.cloud/covers/110x170/CAKSWT.jpg",
		name: "Cakchiquel, Southwestern Yepocapa 2012 Edition",
		bid: "CAKSWT",
	},
	{
		link: "https://amzn.to/2yMw84Y",
		cover: "https://images.bible.cloud/covers/110x170/CAKWSK.jpg",
		name: "New Testament in Kaqchikel, Western Solola",
		bid: "CAKWSK",
	},
	{
		link: "http://amzn.to/2wVZRFG",
		cover: "https://images.bible.cloud/covers/110x170/CAOWBT.jpg",
		name: "The New Testament in Chacobo",
		bid: "CAOWBT",
	},
	{
		link: "http://amzn.to/2f12EXI",
		cover: "https://images.bible.cloud/covers/110x170/CAPSBB.jpg",
		name: "Chipaya 2004 Edition",
		bid: "CAPSBB",
	},
	{
		link: "http://amzn.to/2gWXYmx",
		cover: "https://images.bible.cloud/covers/110x170/CARBSS.jpg",
		name: "Galibi Carib 2003 Edition",
		bid: "CARBSS",
	},
	{
		link: "https://amzn.to/2KbJdKj",
		cover: "https://images.bible.cloud/covers/110x170/CAVWBT.jpg",
		name: "The New Testament in Cavineña",
		bid: "CAVWBT",
	},
	{
		link: "http://amzn.to/2y2cf5A",
		cover: "https://images.bible.cloud/covers/110x170/CAXSBB.jpg",
		name: "The New Testament in Chiquitano 2002",
		bid: "CAXSBB",
	},
	{
		link: "http://amzn.to/2xrZUKG",
		cover: "https://images.bible.cloud/covers/110x170/CBCWBT.jpg",
		name: "Carapana 1992 Edition",
		bid: "CBCWBT",
	},
	{
		link: "https://amzn.to/2twdol8",
		cover: "https://images.bible.cloud/covers/110x170/CBITBL.jpg",
		name: "Genesis, Exodus and the New Testament in Chachi",
		bid: "CBITBL",
	},
	{
		link: "http://amzn.to/2wVYpmw",
		cover: "https://images.bible.cloud/covers/110x170/CBKWBT.jpg",
		name: "The New Testament in Chavacano",
		bid: "CBKWBT",
	},
	{
		link: "http://amzn.to/2wW73l6",
		cover: "https://images.bible.cloud/covers/110x170/CBSWBT.jpg",
		name: "New Testament in Kashinawa for Peru",
		bid: "CBSWBT",
	},
	{
		link: "http://amzn.to/2xsaHo9",
		cover: "https://images.bible.cloud/covers/110x170/CBVTBL.jpg",
		name: "Cacua 2004 Edition",
		bid: "CBVTBL",
	},
	{
		link: "http://amzn.to/2wWNfy1",
		cover: "https://images.bible.cloud/covers/110x170/CCOTBL.jpg",
		name: "Comaltepec Chinantec 2002 Edition",
		bid: "CCOTBL",
	},
	{
		link: "http://amzn.to/2y0Okn3",
		cover: "https://images.bible.cloud/covers/110x170/CGCTBL.jpg",
		name: "Kagayanen 2007 Edition",
		bid: "CGCTBL",
	},
	{
		link: "http://amzn.to/2hdMhEp",
		cover: "https://images.bible.cloud/covers/110x170/CHDWBT.jpg",
		name: "Highland Oaxaca Chontal New Testament",
		bid: "CHDWBT",
	},
	{
		link: "http://amzn.to/2xsjd6M",
		cover: "https://images.bible.cloud/covers/110x170/CHFTBL.jpg",
		name: "Tabasco Chontal 1977 Edition",
		bid: "CHFTBL",
	},
	{
		link: "https://amzn.to/2K7UBa9",
		cover: "https://images.bible.cloud/covers/110x170/CHKBSM.jpg",
		name: "Paipel",
		bid: "CHKBSM",
	},
	{
		link: "http://amzn.to/2y0x55h",
		cover: "https://images.bible.cloud/covers/110x170/CHQBLI.jpg",
		name: "Quiotepec Chinanteco New Testament",
		bid: "CHQBLI",
	},
	{
		link: "http://amzn.to/2gYpLmF",
		cover: "https://images.bible.cloud/covers/110x170/CHZWBT.jpg",
		name: "Ozumacín Chinantec 2003 Edition",
		bid: "CHZWBT",
	},
	{
		link: "https://amzn.to/2K9n6Ed",
		cover: "https://images.bible.cloud/covers/110x170/CJOWBT.jpg",
		name: "The New Testament in Ashéninka Pajonal",
		bid: "CJOWBT",
	},
	{
		link: "http://amzn.to/2jjpUSr",
		cover: "https://images.bible.cloud/covers/110x170/CJVTBL.jpg",
		name: "Chuave 1992 Edition",
		bid: "CJVTBL",
	},
	{
		link: "http://amzn.to/2wW1JxT",
		cover: "https://images.bible.cloud/covers/110x170/CLETBL.jpg",
		name: "Lealao Chinantec 2008 Edition",
		bid: "CLETBL",
	},
	{
		link: "http://amzn.to/2gWALRg",
		cover: "https://images.bible.cloud/covers/110x170/CLUMBB.jpg",
		name: "The New Testament in Caluyanun",
		bid: "CLUMBB",
	},
	{
		link: "http://amzn.to/2y0R184",
		cover: "https://images.bible.cloud/covers/110x170/CMEWBT.jpg",
		name: "Cerma 2011 Edition",
		bid: "CMEWBT",
	},
	{
		link: "http://amzn.to/2wT7m0T",
		cover: "https://images.bible.cloud/covers/110x170/CNLTBI.jpg",
		name: "Chinanteco de Lalana New Testament",
		bid: "CNLTBI",
	},
	{
		link: "https://amzn.to/2tw999c",
		cover: "https://images.bible.cloud/covers/110x170/CNTTBL.jpg",
		name: "Tepetotutla Chinantec 1994 Edition",
		bid: "CNTTBL",
	},
	{
		link: "http://amzn.to/2eRBYoV",
		cover: "https://images.bible.cloud/covers/110x170/COFWBT.jpg",
		name: "Colorado Bible",
		bid: "COFWBT",
	},
	{
		link: "https://amzn.to/2yMF0aI",
		cover: "https://images.bible.cloud/covers/110x170/CONWBT.jpg",
		name: "Cofán 1998 Edition",
		bid: "CONWBT",
	},
	{
		link: "https://amzn.to/2KcneD9",
		cover: "https://images.bible.cloud/covers/110x170/COTTBL.jpg",
		name: "Caquinte 2005 Edition",
		bid: "COTTBL",
	},
	{
		link: "http://amzn.to/2jDmzO7",
		cover: "https://images.bible.cloud/covers/110x170/CPATBL.jpg",
		name: "Palantla Chinantec 1973 Edition",
		bid: "CPATBL",
	},
	{
		link: "http://amzn.to/2gZ30v5",
		cover: "https://images.bible.cloud/covers/110x170/CPBWBT.jpg",
		name: "Ucayali-Yura Ashninka New Testament",
		bid: "CPBWBT",
	},
	{
		link: "http://amzn.to/2gWZ6Gy",
		cover: "https://images.bible.cloud/covers/110x170/CPCWBT.jpg",
		name: "Ajyíninka Apurucayali New Testament",
		bid: "CPCWBT",
	},
	{
		link: "http://amzn.to/2wWl95M",
		cover: "https://images.bible.cloud/covers/110x170/CPUWBT.jpg",
		name: "New Testament in Asheninka Pichis",
		bid: "CPUWBT",
	},
	{
		link: "http://amzn.to/2xt1IT9",
		cover: "https://images.bible.cloud/covers/110x170/CPYWBT.jpg",
		name: "South Ucayali Ashéninka New Testament and Portions",
		bid: "CPYWBT",
	},
	{
		link: "http://amzn.to/2hdPmV0",
		cover: "https://images.bible.cloud/covers/110x170/CRNWBT.jpg",
		name: "The Bible in El Nayar",
		bid: "CRNWBT",
	},
	{
		link: "http://amzn.to/2jjMDNZ",
		cover: "https://images.bible.cloud/covers/110x170/CRXNNT.jpg",
		name: "The New Testament in Nak'albun/Dzinhubun",
		bid: "CRXNNT",
	},
	{
		link: "http://amzn.to/2wT3HA4",
		cover: "https://images.bible.cloud/covers/110x170/CSOTBL.jpg",
		name: "Sochiapam Chinantec 1986 Edition",
		bid: "CSOTBL",
	},
	{
		link: "http://amzn.to/2xtJgth",
		cover: "https://images.bible.cloud/covers/110x170/CTACFB.jpg",
		name: "The Bible in Chatino, Tataltepec",
		bid: "CTACFB",
	},
	{
		link: "https://amzn.to/2twSJ0m",
		cover: "https://images.bible.cloud/covers/110x170/CTPBLI.jpg",
		name: "The Bible in Chatino, Western Highland",
		bid: "CTPBLI",
	},
	{
		link: "http://amzn.to/2w2souq",
		cover: "https://images.bible.cloud/covers/110x170/CUBWBT.jpg",
		name: "The New Testament in Cubeo",
		bid: "CUBWBT",
	},
	{
		link: "http://amzn.to/2xM48gv",
		cover: "https://images.bible.cloud/covers/110x170/CUCTBL.jpg",
		name: "Usila Chinantec 1994 Edition",
		bid: "CUCTBL",
	},
	{
		link: "http://amzn.to/2wThlmV",
		cover: "https://images.bible.cloud/covers/110x170/CUIWBT.jpg",
		name: "Cuiba 1987 Edition",
		bid: "CUIWBT",
	},
	{
		link: "http://amzn.to/2f17ZOK",
		cover: "https://images.bible.cloud/covers/110x170/CUKNVS.jpg",
		name: "The Bible in San Blas Kuna",
		bid: "CUKNVS",
	},
	{
		link: "http://amzn.to/2wWdnZS",
		cover: "https://images.bible.cloud/covers/110x170/CUKWB9.jpg",
		name: "The New Testament in San Blas Kuna",
		bid: "CUKWB9",
	},
	{
		link: "http://amzn.to/2xM710F",
		cover: "https://images.bible.cloud/covers/110x170/CUTWBT.jpg",
		name: "Cuicateco de Teutila New Testament",
		bid: "CUTWBT",
	},
	{
		link: "http://amzn.to/2w2NZme",
		cover: "https://images.bible.cloud/covers/110x170/CUXCFB.jpg",
		name: "The Bible in Cuicatec, Tepeuxila",
		bid: "CUXCFB",
	},
	{
		link: "https://amzn.to/2Kej2CH",
		cover: "https://images.bible.cloud/covers/110x170/CWEPBT.jpg",
		name: "The New Testament in Kwere",
		bid: "CWEPBT",
	},
	{
		link: "http://amzn.to/2w2UQvU",
		cover: "https://images.bible.cloud/covers/110x170/CYAAVV.jpg",
		name: "Nopala Chatino 2000 Edition",
		bid: "CYAAVV",
	},
	{
		link: "http://amzn.to/2xrXn3d",
		cover: "https://images.bible.cloud/covers/110x170/DAAWYI.jpg",
		name: "Dangaléat 2012 Edition",
		bid: "DAAWYI",
	},
	{
		link: "http://amzn.to/2wWlzcr",
		cover: "https://images.bible.cloud/covers/110x170/DAHPNG.jpg",
		name: "The New Testament in Gwahatike",
		bid: "DAHPNG",
	},
	{
		link: "http://amzn.to/2wWqwSu",
		cover: "https://images.bible.cloud/covers/110x170/DEDWBT.jpg",
		name: "Dedua 2005 Edition",
		bid: "DEDWBT",
	},
	{
		link: "http://amzn.to/2f1ok6l",
		cover: "https://images.bible.cloud/covers/110x170/DEUL12.jpg",
		name: "1912 Luther Bible",
		bid: "DEUL12",
	},
	{
		link: "http://amzn.to/2ykqZgb",
		cover: "https://images.bible.cloud/covers/110x170/DGCWBT.jpg",
		name: "New Testament in Agta, Casiguran Dumagat",
		bid: "DGCWBT",
	},
	{
		link: "http://amzn.to/2gXzkCg",
		cover: "https://images.bible.cloud/covers/110x170/DIKTBL.jpg",
		name: "Southwestern Dinka 2006 Edition",
		bid: "DIKTBL",
	},
	{
		link: "http://amzn.to/2wSPSl3",
		cover: "https://images.bible.cloud/covers/110x170/DJKWBT.jpg",
		name: "Eastern Maroon Creole 1999 Edition",
		bid: "DJKWBT",
	},
	{
		link: "http://amzn.to/2w2yc73",
		cover: "https://images.bible.cloud/covers/110x170/DOBPNG.jpg",
		name: "Dobu 1985 Edition",
		bid: "DOBPNG",
	},
	{
		link: "http://amzn.to/2gXfqY1",
		cover: "https://images.bible.cloud/covers/110x170/DWRENT.jpg",
		name: "Dawro 2011 Edition",
		bid: "DWRENT",
	},
	{
		link: "http://amzn.to/2wln8xj",
		cover: "https://images.bible.cloud/covers/110x170/DWRTBL.jpg",
		name: "Dawro 2009 Edition",
		bid: "DWRTBL",
	},
	{
		link: "https://amzn.to/2yMyMrq",
		cover: "https://images.bible.cloud/covers/110x170/DWWTBL.jpg",
		name: "The New Testament in Dawawa",
		bid: "DWWTBL",
	},
	{
		link: "http://amzn.to/2w2NnNC",
		cover: "https://images.bible.cloud/covers/110x170/EBKWBT.jpg",
		name: "The New Testament in Eastern Bontok",
		bid: "EBKWBT",
	},
	{
		link: "http://amzn.to/2xM0O4T",
		cover: "https://images.bible.cloud/covers/110x170/EMPWYI.jpg",
		name: "The New Testament in Northern Emberá",
		bid: "EMPWYI",
	},
	{
		link: "http://amzn.to/2gXU9xm",
		cover: "https://images.bible.cloud/covers/110x170/ENQPNG.jpg",
		name: "The New Testament in Enga",
		bid: "ENQPNG",
	},
	{
		link: "http://amzn.to/2f0DGry",
		cover: "https://images.bible.cloud/covers/110x170/ESEWBT.jpg",
		name: "The New Testament in Ese Ejja",
		bid: "ESEWBT",
	},
	{
		link: "http://amzn.to/2wVETGH",
		cover: "https://images.bible.cloud/covers/110x170/ESKWBT.jpg",
		name: "Northwest Alaska Inupiatun 1997 Edition",
		bid: "ESKWBT",
	},
	{
		link: "https://amzn.to/2KntiEO",
		cover: "https://images.bible.cloud/covers/110x170/ETRTBL.jpg",
		name: "Edolo 2012 Edition",
		bid: "ETRTBL",
	},
	{
		link: "http://amzn.to/2f1nQx4",
		cover: "https://images.bible.cloud/covers/110x170/FAAWBT.jpg",
		name: "Fasu 2012 Edition",
		bid: "FAAWBT",
	},
	{
		link: "https://amzn.to/2yKDjKP",
		cover: "https://images.bible.cloud/covers/110x170/FAIPNG.jpg",
		name: "The New Testament in Faiwol",
		bid: "FAIPNG",
	},
	{
		link: "http://amzn.to/2gZArO4",
		cover: "https://images.bible.cloud/covers/110x170/FFMWBT.jpg",
		name: "The New Testament in Maasina Fulfulde",
		bid: "FFMWBT",
	},
	{
		link: "https://amzn.to/2yQHBQK",
		cover: "https://images.bible.cloud/covers/110x170/FRAOST.jpg",
		name: "Ostervald's French Bible",
		bid: "FRAOST",
	},
	{
		link: "http://amzn.to/2wWt0QO",
		cover: "https://images.bible.cloud/covers/110x170/GAHPNG.jpg",
		name: "The New Testament in Alekano",
		bid: "GAHPNG",
	},
	{
		link: "https://amzn.to/2MsMn9p",
		cover: "https://images.bible.cloud/covers/110x170/GAMWBT.jpg",
		name: "The New Testament in Kandawo",
		bid: "GAMWBT",
	},
	{
		link: "http://amzn.to/2eRLR5I",
		cover: "https://images.bible.cloud/covers/110x170/GAWWBT.jpg",
		name: "Nobonob 1990 Edition",
		bid: "GAWWBT",
	},
	{
		link: "https://amzn.to/2yJCTUX",
		cover: "https://images.bible.cloud/covers/110x170/GDNPNG.jpg",
		name: "Umanakaina 1999 Edition",
		bid: "GDNPNG",
	},
	{
		link: "http://amzn.to/2xtUiP8",
		cover: "https://images.bible.cloud/covers/110x170/GDRPNG.jpg",
		name: "Wipi 2001 Edition",
		bid: "GDRPNG",
	},
	{
		link: "http://amzn.to/2f0py1L",
		cover: "https://images.bible.cloud/covers/110x170/GEBPBT.jpg",
		name: "Fhe Bakimen Kaman Kamej",
		bid: "GEBPBT",
	},
	{
		link: "http://amzn.to/2f0FBfK",
		cover: "https://images.bible.cloud/covers/110x170/GFKTBL.jpg",
		name: "The New Testament in Patpatar",
		bid: "GFKTBL",
	},
	{
		link: "http://amzn.to/2xMp3zX",
		cover: "https://images.bible.cloud/covers/110x170/GHSWBT.jpg",
		name: "The New Testament in Guhu-Samane",
		bid: "GHSWBT",
	},
	{
		link: "http://amzn.to/2wlnBPO",
		cover: "https://images.bible.cloud/covers/110x170/GMVTBL.jpg",
		name: "Gamo 2009 Edition",
		bid: "GMVTBL",
	},
	{
		link: "https://amzn.to/2tMe0CD",
		cover: "https://images.bible.cloud/covers/110x170/GMVWBT.jpg",
		name: "Gamo 2011 Edition",
		bid: "GMVWBT",
	},
	{
		link: "http://amzn.to/2gYjffJ",
		cover: "https://images.bible.cloud/covers/110x170/GNGWYI.jpg",
		name: "Ngangam 2011 Edition",
		bid: "GNGWYI",
	},
	{
		link: "http://amzn.to/2gXBJgg",
		cover: "https://images.bible.cloud/covers/110x170/GNWWBT.jpg",
		name: "Western Bolivian Guarani New Testament (2012)",
		bid: "GNWWBT",
	},
	{
		link: "http://amzn.to/2wmHSEB",
		cover: "https://images.bible.cloud/covers/110x170/GOFE09.jpg",
		name: "Gofa 2009 Edition (Ethiopic script)",
		bid: "GOFE09",
	},
	{
		link: "http://amzn.to/2jkK5PM",
		cover: "https://images.bible.cloud/covers/110x170/GOFTBL.jpg",
		name: "Gofa 2009 Edition (Latin script)",
		bid: "GOFTBL",
	},
	{
		link: "http://amzn.to/2y2sQ99",
		cover: "https://images.bible.cloud/covers/110x170/GUBWBT.jpg",
		name: "Guajajảra 2007 Edition",
		bid: "GUBWBT",
	},
	{
		link: "http://amzn.to/2gYuOU8",
		cover: "https://images.bible.cloud/covers/110x170/GUISBU.jpg",
		name: "Eastern Bolivian Guaraní 2001 Edition",
		bid: "GUISBU",
	},
	{
		link: "http://amzn.to/2wUVKum",
		cover: "https://images.bible.cloud/covers/110x170/GULWBT.jpg",
		name: "The New Testament in Gullah",
		bid: "GULWBT",
	},
	{
		link: "http://amzn.to/2wnfHpg",
		cover: "https://images.bible.cloud/covers/110x170/GUMTBL.jpg",
		name: "Guambiano 2000 Edition",
		bid: "GUMTBL",
	},
	{
		link: "https://amzn.to/2tFQqr0",
		cover: "https://images.bible.cloud/covers/110x170/GUNWBT.jpg",
		name: "Guaraní Mnyá­ 2004 Edition",
		bid: "GUNWBT",
	},
	{
		link: "http://amzn.to/2wXrOeI",
		cover: "https://images.bible.cloud/covers/110x170/GUOWBT.jpg",
		name: "Guayabero WBT Edition",
		bid: "GUOWBT",
	},
	{
		link: "http://amzn.to/2wXYW5O",
		cover: "https://images.bible.cloud/covers/110x170/GVCTBL.jpg",
		name: "Guanano 2007 Edition",
		bid: "GVCTBL",
	},
	{
		link: "https://amzn.to/2tw6Kv4",
		cover: "https://images.bible.cloud/covers/110x170/GVFWBT.jpg",
		name: "Golin 1980 Edition",
		bid: "GVFWBT",
	},
	{
		link: "http://amzn.to/2x3YYe2",
		cover: "https://images.bible.cloud/covers/110x170/GWIG11.jpg",
		name: "Gwichin 2010 Edition",
		bid: "GWIG11",
	},
	{
		link: "http://amzn.to/2fgbpKp",
		cover: "https://images.bible.cloud/covers/110x170/GYMWBT.jpg",
		name: "Ingabere 2004 Edition",
		bid: "GYMWBT",
	},
	{
		link: "http://amzn.to/2xAYb5Y",
		cover: "https://images.bible.cloud/covers/110x170/GYRSBB.jpg",
		name: "The New Testament in Guarayu",
		bid: "GYRSBB",
	},
	{
		link: "https://amzn.to/2twIpp6",
		cover: "https://images.bible.cloud/covers/110x170/HEGWBT.jpg",
		name: "Helong New Testament and Shorter Old Testament",
		bid: "HEGWBT",
	},
	{
		link: "http://amzn.to/2fgtYhK",
		cover: "https://images.bible.cloud/covers/110x170/HLAHNT.jpg",
		name: "The New Testament in Halia",
		bid: "HLAHNT",
	},
	{
		link: "https://amzn.to/2MpIHoR",
		cover: "https://images.bible.cloud/covers/110x170/HMOPNG.jpg",
		name: "Hiri Motu 1994 Edition",
		bid: "HMOPNG",
	},
	{
		link: "https://amzn.to/2KprFGO",
		cover: "https://images.bible.cloud/covers/110x170/HNSWBT.jpg",
		name: "Caribbean Hindustani 1997 Edition",
		bid: "HNSWBT",
	},
	{
		link: "https://amzn.to/2yJqHDL",
		cover: "https://images.bible.cloud/covers/110x170/HOPHNT.jpg",
		name: "Hopi 1977 Edition",
		bid: "HOPHNT",
	},
	{
		link: "http://amzn.to/2wYIK61",
		cover: "https://images.bible.cloud/covers/110x170/HOTWBT.jpg",
		name: "The New Testament in Hote",
		bid: "HOTWBT",
	},
	{
		link: "https://amzn.to/2MrQPVP",
		cover: "https://images.bible.cloud/covers/110x170/HTOWBT.jpg",
		name: "Minica Huitoto 1985 Edition",
		bid: "HTOWBT",
	},
	{
		link: "http://amzn.to/2xvTzOx",
		cover: "https://images.bible.cloud/covers/110x170/HUBWBT.jpg",
		name: "Huambisa 2010 Edition",
		bid: "HUBWBT",
	},
	{
		link: "https://amzn.to/2twO92a",
		cover: "https://images.bible.cloud/covers/110x170/HUIPNG.jpg",
		name: "Huli 2002 Edition",
		bid: "HUIPNG",
	},
	{
		link: "http://amzn.to/2wBuPiN",
		cover: "https://images.bible.cloud/covers/110x170/HUSLLB.jpg",
		name: "Veracruz Huastec 2005 Edition",
		bid: "HUSLLB",
	},
	{
		link: "http://amzn.to/2xgm6Gx",
		cover: "https://images.bible.cloud/covers/110x170/HUSWBT.jpg",
		name: "San Luis Potosi Huastec Edition",
		bid: "HUSWBT",
	},
	{
		link: "https://amzn.to/2lAx7vF",
		cover: "https://images.bible.cloud/covers/110x170/HUUHNT.jpg",
		name: "The New Testament in Huitoto Murui",
		bid: "HUUHNT",
	},
	{
		link: "http://amzn.to/2fvkNKy",
		cover: "https://images.bible.cloud/covers/110x170/HUVTBL.jpg",
		name: "San Mateo Del Mar Huave 1988 Edition",
		bid: "HUVTBL",
	},
	{
		link: "https://amzn.to/2tK8SPo",
		cover: "https://images.bible.cloud/covers/110x170/HVNMRK.jpg",
		name: "Hawu Gospel of Mark",
		bid: "HVNMRK",
	},
	{
		link: "https://amzn.to/2K9f2DA",
		cover: "https://images.bible.cloud/covers/110x170/HWCPGN.jpg",
		name: "The Jesus Book",
		bid: "HWCPGN",
	},
	{
		link: "http://amzn.to/2y3DbBB",
		cover: "https://images.bible.cloud/covers/110x170/IANWBT.jpg",
		name: "The New Testament in Iatmul",
		bid: "IANWBT",
	},
	{
		link: "http://amzn.to/2yjUP4g",
		cover: "https://images.bible.cloud/covers/110x170/IGNSBB.jpg",
		name: "Ignaciano 2004 Edition",
		bid: "IGNSBB",
	},
	{
		link: "http://amzn.to/2wBhjvy",
		cover: "https://images.bible.cloud/covers/110x170/IKKWBT.jpg",
		name: "Revision of New Testament in Ika",
		bid: "IKKWBT",
	},
	{
		link: "http://amzn.to/2f4iTU2",
		cover: "https://images.bible.cloud/covers/110x170/IKWWBT.jpg",
		name: "New Testament in Ikwere",
		bid: "IKWWBT",
	},
	{
		link: "https://amzn.to/2yMbcLs",
		cover: "https://images.bible.cloud/covers/110x170/IMOTBL.jpg",
		name: "Imbongu 1997 Edition",
		bid: "IMOTBL",
	},
	{
		link: "http://amzn.to/2f4oYjf",
		cover: "https://images.bible.cloud/covers/110x170/INOTBL.jpg",
		name: "Inoke-Yate 1992 Edition",
		bid: "INOTBL",
	},
	{
		link: "http://amzn.to/2jlfyBw",
		cover: "https://images.bible.cloud/covers/110x170/IOUTBL.jpg",
		name: "Tuma-Irumu 2011 Edition",
		bid: "IOUTBL",
	},
	{
		link: "http://amzn.to/2wZaEyA",
		cover: "https://images.bible.cloud/covers/110x170/IPILBT.jpg",
		name: "Ipili New Testament",
		bid: "IPILBT",
	},
	{
		link: "https://amzn.to/2N2Toyz",
		cover: "https://images.bible.cloud/covers/110x170/IWSWBT.jpg",
		name: "Sepik Iwam 1989 Edition",
		bid: "IWSWBT",
	},
	{
		link: "http://amzn.to/2xaRMLB",
		cover: "https://images.bible.cloud/covers/110x170/JACWBT.jpg",
		name: "The New Testament in Eastern Jakalteko",
		bid: "JACWBT",
	},
	{
		link: "https://amzn.to/2tGXeEC",
		cover: "https://images.bible.cloud/covers/110x170/JAEYHB.jpg",
		name: "The Holy Bible in Yabem",
		bid: "JAEYHB",
	},
	{
		link: "https://amzn.to/2KnBuIo",
		cover: "https://images.bible.cloud/covers/110x170/JICWBT.jpg",
		name: "Tol 2008 Edition",
		bid: "JICWBT",
	},
	{
		link: "http://amzn.to/2f3q5jv",
		cover: "https://images.bible.cloud/covers/110x170/JIVAIE.jpg",
		name: "Shuar 2009 Edition",
		bid: "JIVAIE",
	},
	{
		link: "http://amzn.to/2wq2Szs",
		cover: "https://images.bible.cloud/covers/110x170/JVNTBL.jpg",
		name: "1999 Edition",
		bid: "JVNTBL",
	},
	{
		link: "https://amzn.to/2KabWPE",
		cover: "https://images.bible.cloud/covers/110x170/KAQWBT.jpg",
		name: "The New Testament in Capanahua",
		bid: "KAQWBT",
	},
	{
		link: "https://amzn.to/2yGWSna",
		cover: "https://images.bible.cloud/covers/110x170/KBCWBT.jpg",
		name: "The New Testament in Kadiw",
		bid: "KBCWBT",
	},
	{
		link: "http://amzn.to/2fvlCTo",
		cover: "https://images.bible.cloud/covers/110x170/KBMTBL.jpg",
		name: "The New Testament in Iwal",
		bid: "KBMTBL",
	},
	{
		link: "https://amzn.to/2yK4ENr",
		cover: "https://images.bible.cloud/covers/110x170/KDCPBT.jpg",
		name: "The New Testament in Kutu",
		bid: "KDCPBT",
	},
	{
		link: "http://amzn.to/2hdnyQJ",
		cover: "https://images.bible.cloud/covers/110x170/KDLWBT.jpg",
		name: "New Testament in Tsikimba",
		bid: "KDLWBT",
	},
	{
		link: "http://amzn.to/2xtBf7W",
		cover: "https://images.bible.cloud/covers/110x170/KEKIBS.jpg",
		name: "Kekchi 2008 Edition",
		bid: "KEKIBS",
	},
	{
		link: "http://amzn.to/2wq3p4e",
		cover: "https://images.bible.cloud/covers/110x170/KENWBT.jpg",
		name: "Kenyang 2010 Edition",
		bid: "KENWBT",
	},
	{
		link: "https://amzn.to/2yQG7pE",
		cover: "https://images.bible.cloud/covers/110x170/KEWPNG.jpg",
		name: "West Kewa 2004 Edition",
		bid: "KEWPNG",
	},
	{
		link: "https://amzn.to/2yQIhWi",
		cover: "https://images.bible.cloud/covers/110x170/KGFGBT.jpg",
		name: "Kube 2007 Edition",
		bid: "KGFGBT",
	},
	{
		link: "http://amzn.to/2wnIOZi",
		cover: "https://images.bible.cloud/covers/110x170/KGKWBT.jpg",
		name: "The New Testament in Kaiwa",
		bid: "KGKWBT",
	},
	{
		link: "https://amzn.to/2K8xHzn",
		cover: "https://images.bible.cloud/covers/110x170/KGPWBT.jpg",
		name: "The New Testament in Kaingang",
		bid: "KGPWBT",
	},
	{
		link: "https://amzn.to/2Kfeaxq",
		cover: "https://images.bible.cloud/covers/110x170/KHZPNG.jpg",
		name: "Keapara 2005 Edition",
		bid: "KHZPNG",
	},
	{
		link: "http://amzn.to/2wZ7I5g",
		cover: "https://images.bible.cloud/covers/110x170/KJEKNT.jpg",
		name: "Kisar New Testament",
		bid: "KJEKNT",
	},
	{
		link: "http://amzn.to/2f3LicV",
		cover: "https://images.bible.cloud/covers/110x170/KJSWBT.jpg",
		name: "The New Testament in East Kewa",
		bid: "KJSWBT",
	},
	{
		link: "http://amzn.to/2ybbnvw",
		cover: "https://images.bible.cloud/covers/110x170/KLVWBT.jpg",
		name: "The New Testament in Maskelynes",
		bid: "KLVWBT",
	},
	{
		link: "https://amzn.to/2ttLZQU",
		cover: "https://images.bible.cloud/covers/110x170/KMGPNT.jpg",
		name: "Portions of the New Testament in Kâte",
		bid: "KMGPNT",
	},
	{
		link: "http://amzn.to/2jCPlyl",
		cover: "https://images.bible.cloud/covers/110x170/KMHMKB.jpg",
		name: "The New Testament in Minimib Kalam",
		bid: "KMHMKB",
	},
	{
		link: "http://amzn.to/2yjRAtC",
		cover: "https://images.bible.cloud/covers/110x170/KMHWBT.jpg",
		name: "The New Testament in Kalam",
		bid: "KMHWBT",
	},
	{
		link: "http://amzn.to/2jCbeOj",
		cover: "https://images.bible.cloud/covers/110x170/KMKWBT.jpg",
		name: "New Testament in Kalinga, Limos",
		bid: "KMKWBT",
	},
	{
		link: "http://amzn.to/2f2QYDU",
		cover: "https://images.bible.cloud/covers/110x170/KMOWBT.jpg",
		name: "The New Testament in Washkuk",
		bid: "KMOWBT",
	},
	{
		link: "http://amzn.to/2y3LFIX",
		cover: "https://images.bible.cloud/covers/110x170/KMSPNG.jpg",
		name: "The New Testament in Kamasau",
		bid: "KMSPNG",
	},
	{
		link: "http://amzn.to/2y2QcM1",
		cover: "https://images.bible.cloud/covers/110x170/KMUWBT.jpg",
		name: "The New Testament in Kanite",
		bid: "KMUWBT",
	},
	{
		link: "https://amzn.to/2Kn3lVP",
		cover: "https://images.bible.cloud/covers/110x170/KNEWBTC.jpg",
		name: "Kankanaey Bible",
		bid: "KNEWBTC",
	},
	{
		link: "http://amzn.to/2wB8W34",
		cover: "https://images.bible.cloud/covers/110x170/KNFWBT.jpg",
		name: "The New Testament in Mankanya",
		bid: "KNFWBT",
	},
	{
		link: "http://amzn.to/2f3gEjJ",
		cover: "https://images.bible.cloud/covers/110x170/KNJWBT.jpg",
		name: "New Testament in Akateko",
		bid: "KNJWBT",
	},
	{
		link: "http://amzn.to/2y3fZU7",
		cover: "https://images.bible.cloud/covers/110x170/KNVARA.jpg",
		name: "Tabo Aramia Dialect Version",
		bid: "KNVARA",
	},
	{
		link: "http://amzn.to/2y2R6bn",
		cover: "https://images.bible.cloud/covers/110x170/KNVPNG.jpg",
		name: "Tabo Fly River Dialect Version",
		bid: "KNVPNG",
	},
	{
		link: "http://amzn.to/2fv6aqG",
		cover: "https://images.bible.cloud/covers/110x170/KPFPNG.jpg",
		name: "The New Testament in Komba",
		bid: "KPFPNG",
	},
	{
		link: "https://amzn.to/2Mp7adO",
		cover: "https://images.bible.cloud/covers/110x170/KPGKPT.jpg",
		name: "The New Testament in Kapingamarangi",
		bid: "KPGKPT",
	},
	{
		link: "http://amzn.to/2fuY0P2",
		cover: "https://images.bible.cloud/covers/110x170/KPRTBL.jpg",
		name: "Korafe-Yegha 2003 Edition",
		bid: "KPRTBL",
	},
	{
		link: "http://amzn.to/2fgCEVi",
		cover: "https://images.bible.cloud/covers/110x170/KPWPNG.jpg",
		name: "The New Testament in Kobon",
		bid: "KPWPNG",
	},
	{
		link: "http://amzn.to/2xfAoXG",
		cover: "https://images.bible.cloud/covers/110x170/KPXTBL.jpg",
		name: "The New Testament in Koiali",
		bid: "KPXTBL",
	},
	{
		link: "https://amzn.to/2Kq0bnB",
		cover: "https://images.bible.cloud/covers/110x170/KQCWBT.jpg",
		name: "The New Testament in Doromu-Koki",
		bid: "KQCWBT",
	},
	{
		link: "https://amzn.to/2KpLpxc",
		cover: "https://images.bible.cloud/covers/110x170/KSRPNG.jpg",
		name: "Borong 2011 Edition",
		bid: "KSRPNG",
	},
	{
		link: "http://amzn.to/2yjJ79Z",
		cover: "https://images.bible.cloud/covers/110x170/KTOPNG.jpg",
		name: "Kuot 2001 Edition",
		bid: "KTOPNG",
	},
	{
		link: "http://amzn.to/2fheU3i",
		cover: "https://images.bible.cloud/covers/110x170/KUEPNG.jpg",
		name: "Kuman 2008 Edition",
		bid: "KUEPNG",
	},
	{
		link: "http://amzn.to/2fhcL7X",
		cover: "https://images.bible.cloud/covers/110x170/KUPTBL.jpg",
		name: "The New Testament in Kunimaipa",
		bid: "KUPTBL",
	},
	{
		link: "http://amzn.to/2xfSg4F",
		cover: "https://images.bible.cloud/covers/110x170/KVNWBT.jpg",
		name: "The New Testament in Border Kuna",
		bid: "KVNWBT",
	},
	{
		link: "http://amzn.to/2wBult2",
		cover: "https://images.bible.cloud/covers/110x170/KWDWBT.jpg",
		name: "The New Testament in Kwaio",
		bid: "KWDWBT",
	},
	{
		link: "https://amzn.to/2ttI1Yy",
		cover: "https://images.bible.cloud/covers/110x170/KWIWBT.jpg",
		name: "Awa-Cuaiquer 2002 Edition",
		bid: "KWIWBT",
	},
	{
		link: "https://amzn.to/2MsTeQ7",
		cover: "https://images.bible.cloud/covers/110x170/KWJWBT.jpg",
		name: "Kwanga New Testament",
		bid: "KWJWBT",
	},
	{
		link: "https://amzn.to/2yFSvsC",
		cover: "https://images.bible.cloud/covers/110x170/KYCPNG.jpg",
		name: "Kyaka Bible Society Version",
		bid: "KYCPNG",
	},
	{
		link: "http://amzn.to/2wAVPiq",
		cover: "https://images.bible.cloud/covers/110x170/KYFWBT.jpg",
		name: "Kouya 2002 Edition",
		bid: "KYFWBT",
	},
	{
		link: "http://amzn.to/2yjNUZ7",
		cover: "https://images.bible.cloud/covers/110x170/KYGTBL.jpg",
		name: "Keyagana 2013 Edition",
		bid: "KYGTBL",
	},
	{
		link: "http://amzn.to/2jmo2bm",
		cover: "https://images.bible.cloud/covers/110x170/KYQWBT.jpg",
		name: "Kenga 2012 Edition",
		bid: "KYQWBT",
	},
	{
		link: "http://amzn.to/2y4UxOS",
		cover: "https://images.bible.cloud/covers/110x170/KYZWBT.jpg",
		name: "Kayabí­ 1999 Edition",
		bid: "KYZWBT",
	},
	{
		link: "http://amzn.to/2yjDF73",
		cover: "https://images.bible.cloud/covers/110x170/KZEWBT.jpg",
		name: "Kosena 1980 Edition",
		bid: "KZEWBT",
	},
	{
		link: "http://amzn.to/2wAWWi6",
		cover: "https://images.bible.cloud/covers/110x170/LACTBL.jpg",
		name: "The New Testament in Lacandon",
		bid: "LACTBL",
	},
	{
		link: "https://amzn.to/2yK8shH",
		cover: "https://images.bible.cloud/covers/110x170/LBBWBT.jpg",
		name: "The Gospel According to Mark in Label",
		bid: "LBBWBT",
	},
	{
		link: "http://amzn.to/2f4Brn8",
		cover: "https://images.bible.cloud/covers/110x170/LBKWBT.jpg",
		name: "The New Testament in Bontok",
		bid: "LBKWBT",
	},
	{
		link: "http://amzn.to/2jFTSjG",
		cover: "https://images.bible.cloud/covers/110x170/LCMPNG.jpg",
		name: "Tungag 2011 Edition",
		bid: "LCMPNG",
	},
	{
		link: "http://amzn.to/2wnXQhO",
		cover: "https://images.bible.cloud/covers/110x170/LEUPNG.jpg",
		name: "Kara 1997 Edition",
		bid: "LEUPNG",
	},
	{
		link: "http://amzn.to/2jlUIly",
		cover: "https://images.bible.cloud/covers/110x170/LEXWBT.jpg",
		name: "Luang New Testament and Portions",
		bid: "LEXWBT",
	},
	{
		link: "http://amzn.to/2fkUBSH",
		cover: "https://images.bible.cloud/covers/110x170/LIDWBT.jpg",
		name: "The New Testament in Nyndrou",
		bid: "LIDWBT",
	},
	{
		link: "http://amzn.to/2xvDMPx",
		cover: "https://images.bible.cloud/covers/110x170/LIFWBT.jpg",
		name: "Limbu 2009 Edition",
		bid: "LIFWBT",
	},
	{
		link: "http://amzn.to/2f80m9k",
		cover: "https://images.bible.cloud/covers/110x170/MAASJV.jpg",
		name: "San Jerónimo Tecuanipan Mazatec 2012 (San Jeronimo)",
		bid: "MAASJV",
	},
	{
		link: "http://amzn.to/2wY1e5a",
		cover: "https://images.bible.cloud/covers/110x170/MAJBTT.jpg",
		name: "Portions of the Bible in Jalapa de Díaz Mazatec",
		bid: "MAJBTT",
	},
	{
		link: "http://amzn.to/2w6ggby",
		cover: "https://images.bible.cloud/covers/110x170/MAMCOM.jpg",
		name: "Mam Central 2009 Edition",
		bid: "MAMCOM",
	},
	{
		link: "http://amzn.to/2f8IXNO",
		cover: "https://images.bible.cloud/covers/110x170/MAMSBG.jpg",
		name: "Todos Santos Mam 2000 Edition",
		bid: "MAMSBG",
	},
	{
		link: "http://amzn.to/2jqe7BL",
		cover: "https://images.bible.cloud/covers/110x170/MAQTBL.jpg",
		name: "Chiquihuite Mazatec 1991 Edition",
		bid: "MAQTBL",
	},
	{
		link: "http://amzn.to/2f4qgem",
		cover: "https://images.bible.cloud/covers/110x170/MAUWBT.jpg",
		name: "The New Testament in Huautla Mazatec",
		bid: "MAUWBT",
	},
	{
		link: "http://amzn.to/2jn5kjP",
		cover: "https://images.bible.cloud/covers/110x170/MAVWBT.jpg",
		name: "The New Testament in Sateré-Mawé",
		bid: "MAVWBT",
	},
	{
		link: "http://amzn.to/2xwhspc",
		cover: "https://images.bible.cloud/covers/110x170/MAZTBL.jpg",
		name: "Central Mazahua 2007 Edition",
		bid: "MAZTBL",
	},
	{
		link: "http://amzn.to/2xwibGY",
		cover: "https://images.bible.cloud/covers/110x170/MBCWBT.jpg",
		name: "The New Testament in Macushi",
		bid: "MBCWBT",
	},
	{
		link: "http://amzn.to/2eYbn9C",
		cover: "https://images.bible.cloud/covers/110x170/MBHTBL.jpg",
		name: "The New Testament in Mangseng",
		bid: "MBHTBL",
	},
	{
		link: "https://amzn.to/2N09poU",
		cover: "https://images.bible.cloud/covers/110x170/MBJWBT.jpg",
		name: "The New Testament in Nadeb",
		bid: "MBJWBT",
	},
	{
		link: "http://amzn.to/2xvSTc3",
		cover: "https://images.bible.cloud/covers/110x170/MBLWBT.jpg",
		name: "The New Testament in Maxakali",
		bid: "MBLWBT",
	},
	{
		link: "http://amzn.to/2xw9fkJ",
		cover: "https://images.bible.cloud/covers/110x170/MBSWBT.jpg",
		name: "The New Testament in Sarangani Manobo",
		bid: "MBSWBT",
	},
	{
		link: "http://amzn.to/2wXPTBX",
		cover: "https://images.bible.cloud/covers/110x170/MBTWBT.jpg",
		name: "The New Testament in Matigsalug Manobo",
		bid: "MBTWBT",
	},
	{
		link: "http://amzn.to/2xvGF2X",
		cover: "https://images.bible.cloud/covers/110x170/MCAWBT.jpg",
		name: "The New Testament in Maca",
		bid: "MCAWBT",
	},
	{
		link: "http://amzn.to/2eYa9v6",
		cover: "https://images.bible.cloud/covers/110x170/MCDWBT.jpg",
		name: "The New Testament in Sharanahua",
		bid: "MCDWBT",
	},
	{
		link: "http://amzn.to/2wYwjpl",
		cover: "https://images.bible.cloud/covers/110x170/MCFWBT.jpg",
		name: "The New Testament in Matsés",
		bid: "MCFWBT",
	},
	{
		link: "http://amzn.to/2xuJpxq",
		cover: "https://images.bible.cloud/covers/110x170/MCQSPP.jpg",
		name: "The New Testament in Ese",
		bid: "MCQSPP",
	},
	{
		link: "http://amzn.to/2wCbiil",
		cover: "https://images.bible.cloud/covers/110x170/MEDPNG.jpg",
		name: "Melpa 1995 Edition",
		bid: "MEDPNG",
	},
	{
		link: "http://amzn.to/2woidvb",
		cover: "https://images.bible.cloud/covers/110x170/MEETBL.jpg",
		name: "Mengen 2003 Edition",
		bid: "MEETBL",
	},
	{
		link: "http://amzn.to/2wCoiUW",
		cover: "https://images.bible.cloud/covers/110x170/MEKPNG.jpg",
		name: "The New Testament in Mekeo",
		bid: "MEKPNG",
	},
	{
		link: "http://amzn.to/2wZAlPV",
		cover: "https://images.bible.cloud/covers/110x170/MEQWBT.jpg",
		name: "Merey 2012 Edition",
		bid: "MEQWBT",
	},
	{
		link: "http://amzn.to/2f82KNk",
		cover: "https://images.bible.cloud/covers/110x170/MGHWBT.jpg",
		name: "The New Testament in the Makhuwa-Meetto",
		bid: "MGHWBT",
	},
	{
		link: "http://amzn.to/2jnhucE",
		cover: "https://images.bible.cloud/covers/110x170/MHLPNG.jpg",
		name: "Mauwake 1998 Edition",
		bid: "MHLPNG",
	},
	{
		link: "http://amzn.to/2y9sMEI",
		cover: "https://images.bible.cloud/covers/110x170/MIBWBT.jpg",
		name: "The New Testament of Mixtec, Atatláhuca",
		bid: "MIBWBT",
	},
	{
		link: "http://amzn.to/2wnYFao",
		cover: "https://images.bible.cloud/covers/110x170/MIETBL.jpg",
		name: "Ocotepec Mixtec 1977 Edition",
		bid: "MIETBL",
	},
	{
		link: "http://amzn.to/2wZPVf8",
		cover: "https://images.bible.cloud/covers/110x170/MIGWBT.jpg",
		name: "San Miguel Grande Mixtec New Testament",
		bid: "MIGWBT",
	},
	{
		link: "http://amzn.to/2jtCdvh",
		cover: "https://images.bible.cloud/covers/110x170/MIHWBT.jpg",
		name: "The New Testament in Mixtec, Chayuco",
		bid: "MIHWBT",
	},
	{
		link: "http://amzn.to/2x4IVN8",
		cover: "https://images.bible.cloud/covers/110x170/MILTBL.jpg",
		name: "Mixtec Penoles 2002 Edition",
		bid: "MILTBL",
	},
	{
		link: "http://amzn.to/2jsTHrV",
		cover: "https://images.bible.cloud/covers/110x170/MIOWBT.jpg",
		name: "Pinotepa Nacional Mixtec 2013 Edition",
		bid: "MIOWBT",
	},
	{
		link: "http://amzn.to/2f4GB2A",
		cover: "https://images.bible.cloud/covers/110x170/MIRTBL.jpg",
		name: "Isthmus Mixe 1988 Edition",
		bid: "MIRTBL",
	},
	{
		link: "http://amzn.to/2xvW4jY",
		cover: "https://images.bible.cloud/covers/110x170/MITTBL.jpg",
		name: "Southern Puebla Mixtec 1978 Edition",
		bid: "MITTBL",
	},
	{
		link: "http://amzn.to/2xwzNlK",
		cover: "https://images.bible.cloud/covers/110x170/MIZTBL.jpg",
		name: "Coatzospan Mixtec 2003 Edition",
		bid: "MIZTBL",
	},
	{
		link: "http://amzn.to/2wco1gr",
		cover: "https://images.bible.cloud/covers/110x170/MJCWBT.jpg",
		name: "San Juan Colorado Mixtec New Testament",
		bid: "MJCWBT",
	},
	{
		link: "http://amzn.to/2xwir8U",
		cover: "https://images.bible.cloud/covers/110x170/MKSTBL.jpg",
		name: "Silacayoapan Mixtec 1999 Edition",
		bid: "MKSTBL",
	},
	{
		link: "http://amzn.to/2xwjAxc",
		cover: "https://images.bible.cloud/covers/110x170/MLHPNG.jpg",
		name: "The New Testament in Mape",
		bid: "MLHPNG",
	},
	{
		link: "http://amzn.to/2wZB8Qy",
		cover: "https://images.bible.cloud/covers/110x170/MLPTBL.jpg",
		name: "Bargam 2002 Edition",
		bid: "MLPTBL",
	},
	{
		link: "http://amzn.to/2wo751B",
		cover: "https://images.bible.cloud/covers/110x170/MMXTBL.jpg",
		name: "The New Testament and Psalms in Madak",
		bid: "MMXTBL",
	},
	{
		link: "https://amzn.to/2KptpTm",
		cover: "https://images.bible.cloud/covers/110x170/MNAPNG.jpg",
		name: "The New Testament in Mbula",
		bid: "MNAPNG",
	},
	{
		link: "http://amzn.to/2x5iVRT",
		cover: "https://images.bible.cloud/covers/110x170/MOPWBT.jpg",
		name: "Mopán Maya 2004 Edition",
		bid: "MOPWBT",
	},
	{
		link: "http://amzn.to/2wo7bX1",
		cover: "https://images.bible.cloud/covers/110x170/MPMTBL.jpg",
		name: "Mixtec, Yosondúa 2010 Edition",
		bid: "MPMTBL",
	},
	{
		link: "http://amzn.to/2f4H1Gc",
		cover: "https://images.bible.cloud/covers/110x170/MPTTBL.jpg",
		name: "Mian 1986 Edition",
		bid: "MPTTBL",
	},
	{
		link: "http://amzn.to/2w60M7y",
		cover: "https://images.bible.cloud/covers/110x170/MPXPNG.jpg",
		name: "Misima-Paneati 1997 Edition",
		bid: "MPXPNG",
	},
	{
		link: "http://amzn.to/2jmTDd1",
		cover: "https://images.bible.cloud/covers/110x170/MQBWBT.jpg",
		name: "Mbuko 2010 Edition",
		bid: "MQBWBT",
	},
	{
		link: "http://amzn.to/2f2QTAf",
		cover: "https://images.bible.cloud/covers/110x170/MSBWBT.jpg",
		name: "The New Testament in Masbatenyo",
		bid: "MSBWBT",
	},
	{
		link: "https://amzn.to/2tzPXGK",
		cover: "https://images.bible.cloud/covers/110x170/MSCPBT.jpg",
		name: "Sankaran Maninka Bible Portions",
		bid: "MSCPBT",
	},
	{
		link: "http://amzn.to/2x4amqo",
		cover: "https://images.bible.cloud/covers/110x170/MSKWBT.jpg",
		name: "The New Testament in Mansaka",
		bid: "MSKWBT",
	},
	{
		link: "http://amzn.to/2jlVS0o",
		cover: "https://images.bible.cloud/covers/110x170/MSMWPS.jpg",
		name: "Agusan Manobo 1999 Edition",
		bid: "MSMWPS",
	},
	{
		link: "https://amzn.to/2tGzNLR",
		cover: "https://images.bible.cloud/covers/110x170/MSYPNG.jpg",
		name: "Aruamu 2004 Edition",
		bid: "MSYPNG",
	},
	{
		link: "http://amzn.to/2w6h4gL",
		cover: "https://images.bible.cloud/covers/110x170/MTITBL.jpg",
		name: "The New Testament in Maiwa",
		bid: "MTITBL",
	},
	{
		link: "http://amzn.to/2wo3Ffn",
		cover: "https://images.bible.cloud/covers/110x170/MUYWBT.jpg",
		name: "Muyang 2013 Edition",
		bid: "MUYWBT",
	},
	{
		link: "https://amzn.to/2Ka9fxy",
		cover: "https://images.bible.cloud/covers/110x170/MWCWBT.jpg",
		name: "The Gospel of Luke in Are",
		bid: "MWCWBT",
	},
	{
		link: "http://amzn.to/2fkPUbo",
		cover: "https://images.bible.cloud/covers/110x170/MXBMVR.jpg",
		name: "Mixtec de Tezoatlan 2006 Edition",
		bid: "MXBMVR",
	},
	{
		link: "http://amzn.to/2y8XkGs",
		cover: "https://images.bible.cloud/covers/110x170/MXPWBT.jpg",
		name: "Tlahuitoltepec Mixe New Testament",
		bid: "MXPWBT",
	},
	{
		link: "https://amzn.to/2tKaBEm",
		cover: "https://images.bible.cloud/covers/110x170/MXQTBL.jpg",
		name: "Juquila Mixe 2004 Edition",
		bid: "MXQTBL",
	},
	{
		link: "http://amzn.to/2jtk2WM",
		cover: "https://images.bible.cloud/covers/110x170/MXTTBL.jpg",
		name: "Jamiltepec Mixtec 1983 Edition",
		bid: "MXTTBL",
	},
	{
		link: "http://amzn.to/2xvSRka",
		cover: "https://images.bible.cloud/covers/110x170/MYKWBT.jpg",
		name: "Mamara Senoufo 2006 Edition",
		bid: "MYKWBT",
	},
	{
		link: "http://amzn.to/2x4SkEn",
		cover: "https://images.bible.cloud/covers/110x170/MYUWBT.jpg",
		name: "The New Testament in Munduruk",
		bid: "MYUWBT",
	},
	{
		link: "http://amzn.to/2xvJXDf",
		cover: "https://images.bible.cloud/covers/110x170/MYWPNG.jpg",
		name: "Muyuw 1993 Edition",
		bid: "MYWPNG",
	},
	{
		link: "http://amzn.to/2jntR8F",
		cover: "https://images.bible.cloud/covers/110x170/MYYWBT.jpg",
		name: "New Testament in Macuna",
		bid: "MYYWBT",
	},
	{
		link: "http://amzn.to/2wZ9R0F",
		cover: "https://images.bible.cloud/covers/110x170/NABWBT.jpg",
		name: "The New Testament in Nambikuara",
		bid: "NABWBT",
	},
	{
		link: "http://amzn.to/2eZ7Isi",
		cover: "https://images.bible.cloud/covers/110x170/NAFTBL.jpg",
		name: "Nabak 1988 Edition",
		bid: "NAFTBL",
	},
	{
		link: "http://amzn.to/2xvUyOH",
		cover: "https://images.bible.cloud/covers/110x170/NAKTBL.jpg",
		name: "Nakanai 1983 Edition",
		bid: "NAKTBL",
	},
	{
		link: "http://amzn.to/2wrxpN3",
		cover: "https://images.bible.cloud/covers/110x170/NASPNG.jpg",
		name: "Naasioi 1994 Edition",
		bid: "NASPNG",
	},
	{
		link: "https://amzn.to/2KpZWcb",
		cover: "https://images.bible.cloud/covers/110x170/NCAWBT.jpg",
		name: "The New Testament in Iyo",
		bid: "NCAWBT",
	},
	{
		link: "http://amzn.to/2x4KCud",
		cover: "https://images.bible.cloud/covers/110x170/NCHTBL.jpg",
		name: "Central Huasteca Nahuatl 2005 Edition",
		bid: "NCHTBL",
	},
	{
		link: "http://amzn.to/2f7JCz6",
		cover: "https://images.bible.cloud/covers/110x170/NCLTBL.jpg",
		name: "New Testament in Mixtec, Michoacán",
		bid: "NCLTBL",
	},
	{
		link: "http://amzn.to/2eYKVwp",
		cover: "https://images.bible.cloud/covers/110x170/NCUWBT.jpg",
		name: "Chumburung 1988 Edition",
		bid: "NCUWBT",
	},
	{
		link: "https://amzn.to/2K7YID7",
		cover: "https://images.bible.cloud/covers/110x170/NFAUBB.jpg",
		name: "God's Word in Dhao",
		bid: "NFAUBB",
	},
	{
		link: "https://amzn.to/2tvaj4K",
		cover: "https://images.bible.cloud/covers/110x170/NGUTBL.jpg",
		name: "The New Testament in Guerrero Nahuatl",
		bid: "NGUTBL",
	},
	{
		link: "http://amzn.to/2fkuyuP",
		cover: "https://images.bible.cloud/covers/110x170/NHETBL.jpg",
		name: "Eastern Huasteca Nahuatl 2005 Edition",
		bid: "NHETBL",
	},
	{
		link: "http://amzn.to/2wC4L78",
		cover: "https://images.bible.cloud/covers/110x170/NHEWBT.jpg",
		name: "New Testament in Nahuatl, Huasteca Oriental",
		bid: "NHEWBT",
	},
	{
		link: "http://amzn.to/2wZhWT7",
		cover: "https://images.bible.cloud/covers/110x170/NHGWBT.jpg",
		name: "The New Testament in Tetelcingo Nahuatl",
		bid: "NHGWBT",
	},
	{
		link: "https://amzn.to/2KnhSUD",
		cover: "https://images.bible.cloud/covers/110x170/NHIWBT.jpg",
		name: "Nahuatl Zacatlán-Aztec New Testament",
		bid: "NHIWBT",
	},
	{
		link: "http://amzn.to/2jqy4Iu",
		cover: "https://images.bible.cloud/covers/110x170/NHUWBT.jpg",
		name: "Noone 2011 Edition",
		bid: "NHUWBT",
	},
	{
		link: "http://amzn.to/2x4Icvl",
		cover: "https://images.bible.cloud/covers/110x170/NHYTBL.jpg",
		name: "Northern Oaxaca Nahuatl 2006 Edition",
		bid: "NHYTBL",
	},
	{
		link: "https://amzn.to/2yFT9Gy",
		cover: "https://images.bible.cloud/covers/110x170/NIFWBT.jpg",
		name: "The Gospels in Nek",
		bid: "NIFWBT",
	},
	{
		link: "http://amzn.to/2f2Froc",
		cover: "https://images.bible.cloud/covers/110x170/NINWBT.jpg",
		name: "The New Testament in Ninzo",
		bid: "NINWBT",
	},
	{
		link: "https://amzn.to/2KjX5BD",
		cover: "https://images.bible.cloud/covers/110x170/NOAWBE.jpg",
		name: "New Testament in Wounaan (Alternate Orthography)",
		bid: "NOAWBE",
	},
	{
		link: "https://amzn.to/2Kqmvxl",
		cover: "https://images.bible.cloud/covers/110x170/NOPNTT.jpg",
		name: "New Testament in Numanggang",
		bid: "NOPNTT",
	},
	{
		link: "http://amzn.to/2xBtIF1",
		cover: "https://images.bible.cloud/covers/110x170/NOTWBT.jpg",
		name: "The New Testament in Nomatsiguenga (2004)",
		bid: "NOTWBT",
	},
	{
		link: "http://amzn.to/2xBCRxb",
		cover: "https://images.bible.cloud/covers/110x170/NOUTBL.jpg",
		name: "Ewage-Notu 1987 Edition",
		bid: "NOUTBL",
	},
	{
		link: "http://amzn.to/2f9g8Rz",
		cover: "https://images.bible.cloud/covers/110x170/NSNWBT.jpg",
		name: "Nehan 2011 Edition",
		bid: "NSNWBT",
	},
	{
		link: "http://amzn.to/2f97wud",
		cover: "https://images.bible.cloud/covers/110x170/NTPTBL.jpg",
		name: "Northern Tepehuan 1981 Edition",
		bid: "NTPTBL",
	},
	{
		link: "http://amzn.to/2woicHJ",
		cover: "https://images.bible.cloud/covers/110x170/NVMWBT.jpg",
		name: "Namiae 2004 Edition",
		bid: "NVMWBT",
	},
	{
		link: "http://amzn.to/2xvT8DI",
		cover: "https://images.bible.cloud/covers/110x170/NWIWBT.jpg",
		name: "The New Testament in Nivhaar",
		bid: "NWIWBT",
	},
	{
		link: "https://amzn.to/2IroXi8",
		cover: "https://images.bible.cloud/covers/110x170/OBOWBT.jpg",
		name: "The New Testament in Manobo, Obo",
		bid: "OBOWBT",
	},
	{
		link: "http://amzn.to/2x3NFmc",
		cover: "https://images.bible.cloud/covers/110x170/OKVWBT.jpg",
		name: "Orokaiva 1988 Edition",
		bid: "OKVWBT",
	},
	{
		link: "https://amzn.to/2tFOqz0",
		cover: "https://images.bible.cloud/covers/110x170/OMWWBT.jpg",
		name: "The New Testament in South Tairora",
		bid: "OMWWBT",
	},
	{
		link: "https://amzn.to/2Iufcjn",
		cover: "https://images.bible.cloud/covers/110x170/ONGTBL.jpg",
		name: "The New Testament in Olo",
		bid: "ONGTBL",
	},
	{
		link: "http://amzn.to/2jFqUQU",
		cover: "https://images.bible.cloud/covers/110x170/ONSONT.jpg",
		name: "The New Testament in Ono",
		bid: "ONSONT",
	},
	{
		link: "https://amzn.to/2tKa6ds",
		cover: "https://images.bible.cloud/covers/110x170/OODTBL.jpg",
		name: "Tohono O'odham 1975 Edition",
		bid: "OODTBL",
	},
	{
		link: "https://amzn.to/2tvYTxN",
		cover: "https://images.bible.cloud/covers/110x170/OPMTBL.jpg",
		name: "Oksapmin 1992 Edition",
		bid: "OPMTBL",
	},
	{
		link: "http://amzn.to/2x435GY",
		cover: "https://images.bible.cloud/covers/110x170/OTETBL.jpg",
		name: "Mezquital Otomi 1990 Edition",
		bid: "OTETBL",
	},
	{
		link: "http://amzn.to/2jsJvzn",
		cover: "https://images.bible.cloud/covers/110x170/OTMWBT.jpg",
		name: "The New Testament in Otomi",
		bid: "OTMWBT",
	},
	{
		link: "http://amzn.to/2x4KYAG",
		cover: "https://images.bible.cloud/covers/110x170/OTNWBT.jpg",
		name: "The New Testament in Otomi, Tenango",
		bid: "OTNWBT",
	},
	{
		link: "http://amzn.to/2x4P6kv",
		cover: "https://images.bible.cloud/covers/110x170/OTQTBL.jpg",
		name: "Queretaro Otomi 2003 Edition",
		bid: "OTQTBL",
	},
	{
		link: "http://amzn.to/2f97h2e",
		cover: "https://images.bible.cloud/covers/110x170/OTSWBT.jpg",
		name: "Estado de México Otomi New Testament",
		bid: "OTSWBT",
	},
	{
		link: "http://amzn.to/2xBzg2i",
		cover: "https://images.bible.cloud/covers/110x170/PABTBL.jpg",
		name: "The New Testament in Parecis",
		bid: "PABTBL",
	},
	{
		link: "https://amzn.to/2tEkV0A",
		cover: "https://images.bible.cloud/covers/110x170/PADWBT.jpg",
		name: "The New Testament in Paumari",
		bid: "PADWBT",
	},
	{
		link: "https://amzn.to/2KtlCUZ",
		cover: "https://images.bible.cloud/covers/110x170/PAHTBL.jpg",
		name: "Tenharim 1996 Edition",
		bid: "PAHTBL",
	},
	{
		link: "https://amzn.to/2txCLTs",
		cover: "https://images.bible.cloud/covers/110x170/PAONAB.jpg",
		name: "Northern Paiute 1985 Edition",
		bid: "PAONAB",
	},
	{
		link: "http://amzn.to/2wYOsTM",
		cover: "https://images.bible.cloud/covers/110x170/PIBWBT.jpg",
		name: "The New Testament in Yine",
		bid: "PIBWBT",
	},
	{
		link: "http://amzn.to/2wnVteS",
		cover: "https://images.bible.cloud/covers/110x170/PIOWBT.jpg",
		name: "The New Testament in Piapoco",
		bid: "PIOWBT",
	},
	{
		link: "https://amzn.to/2tEprvS",
		cover: "https://images.bible.cloud/covers/110x170/PIRWBT.jpg",
		name: "Piratapuyo 1990 Edition",
		bid: "PIRWBT",
	},
	{
		link: "http://amzn.to/2f2YHSv",
		cover: "https://images.bible.cloud/covers/110x170/PLUWBT.jpg",
		name: "The New Testament in Palikr",
		bid: "PLUWBT",
	},
	{
		link: "https://amzn.to/2MsSSsL",
		cover: "https://images.bible.cloud/covers/110x170/PMAWBT.jpg",
		name: "Paama Bible",
		bid: "PMAWBT",
	},
	{
		link: "http://amzn.to/2f8Ga7o",
		cover: "https://images.bible.cloud/covers/110x170/POETBL.jpg",
		name: "San Juan Atzingo Popoloca 1982 Edition",
		bid: "POETBL",
	},
	{
		link: "https://amzn.to/2tvdzgj",
		cover: "https://images.bible.cloud/covers/110x170/POHBSG.jpg",
		name: "Poqomchi' 2009 Edition",
		bid: "POHBSG",
	},
	{
		link: "http://amzn.to/2wnKGl9",
		cover: "https://images.bible.cloud/covers/110x170/POIWBT.jpg",
		name: "Highland Popoluca New Testament (1997)",
		bid: "POIWBT",
	},
	{
		link: "https://amzn.to/2Kn4HmQ",
		cover: "https://images.bible.cloud/covers/110x170/POYPNT.jpg",
		name: "The New Testament in Pogolo",
		bid: "POYPNT",
	},
	{
		link: "http://amzn.to/2f4sfiO",
		cover: "https://images.bible.cloud/covers/110x170/PPOYKS.jpg",
		name: "The New Testament in Folopa",
		bid: "PPOYKS",
	},
	{
		link: "http://amzn.to/2xAZbHg",
		cover: "https://images.bible.cloud/covers/110x170/PTPWBT.jpg",
		name: "Patep 1986 Edition",
		bid: "PTPWBT",
	},
	{
		link: "http://amzn.to/2f3assm",
		cover: "https://images.bible.cloud/covers/110x170/PTULAI.jpg",
		name: "Bambam 2004 Edition",
		bid: "PTULAI",
	},
	{
		link: "http://amzn.to/2wZse5Q",
		cover: "https://images.bible.cloud/covers/110x170/PWGWBT.jpg",
		name: "Gapapaiwa 2009 Edition",
		bid: "PWGWBT",
	},
	{
		link: "http://amzn.to/2wZC5Zu",
		cover: "https://images.bible.cloud/covers/110x170/QUBPBS.jpg",
		name: "Huallaga Quechua WBT Version",
		bid: "QUBPBS",
	},
	{
		link: "http://amzn.to/2wYzEEE",
		cover: "https://images.bible.cloud/covers/110x170/QUCWBT.jpg",
		name: "K'iche' New Testament (New Spelling)",
		bid: "QUCWBT",
	},
	{
		link: "http://amzn.to/2wnvSTy",
		cover: "https://images.bible.cloud/covers/110x170/QUCXIBS.jpg",
		name: "Quiche New Testament (Ximénez)",
		bid: "QUCXIBS",
	},
	{
		link: "https://amzn.to/2yKxqNQ",
		cover: "https://images.bible.cloud/covers/110x170/QUFLLB.jpg",
		name: "The New Testament in Quechua, Lambayeque",
		bid: "QUFLLB",
	},
	{
		link: "http://amzn.to/2wnRAqp",
		cover: "https://images.bible.cloud/covers/110x170/QUHSBB.jpg",
		name: "South Bolivian Quechua 1993 Edition",
		bid: "QUHSBB",
	},
	{
		link: "http://amzn.to/2f7ZoKe",
		cover: "https://images.bible.cloud/covers/110x170/QUPTBL.jpg",
		name: "Southern Pastaza Quechua 1997 Edition",
		bid: "QUPTBL",
	},
	{
		link: "https://amzn.to/2tCGvCx",
		cover: "https://images.bible.cloud/covers/110x170/QVCTBL.jpg",
		name: "Cajamarca Quechua 2004 Edition",
		bid: "QVCTBL",
	},
	{
		link: "http://amzn.to/2jmCOyU",
		cover: "https://images.bible.cloud/covers/110x170/QVETBL.jpg",
		name: "Eastern Apurimac Quechua WBT Version",
		bid: "QVETBL",
	},
	{
		link: "http://amzn.to/2jsY2eJ",
		cover: "https://images.bible.cloud/covers/110x170/QVNLLB.jpg",
		name: "North Junin Quechua 1997 Edition",
		bid: "QVNLLB",
	},
	{
		link: "https://amzn.to/2Kab1yG",
		cover: "https://images.bible.cloud/covers/110x170/QVSTBL.jpg",
		name: "San Marti­n Quechua 1992 Edition",
		bid: "QVSTBL",
	},
	{
		link: "http://amzn.to/2wZbUC1",
		cover: "https://images.bible.cloud/covers/110x170/QVWTBL.jpg",
		name: "Huaylla Wanca Quechua 2006 Edition",
		bid: "QVWTBL",
	},
	{
		link: "https://amzn.to/2txhEAL",
		cover: "https://images.bible.cloud/covers/110x170/QVZWBT.jpg",
		name: "Northern Pastaza Quichua 1992 Edition",
		bid: "QVZWBT",
	},
	{
		link: "http://amzn.to/2wYZV5S",
		cover: "https://images.bible.cloud/covers/110x170/QWHLLB.jpg",
		name: "Huaylas Ancash Quechua 2007 Edition",
		bid: "QWHLLB",
	},
	{
		link: "http://amzn.to/2xv3weR",
		cover: "https://images.bible.cloud/covers/110x170/QXHWBT.jpg",
		name: "Panao Huánuco Quechua 2009 Edition",
		bid: "QXHWBT",
	},
	{
		link: "https://amzn.to/2lCohO0",
		cover: "https://images.bible.cloud/covers/110x170/QXNWBT.jpg",
		name: "Northern Conchucos Ancash Quechua 2006 Edition",
		bid: "QXNWBT",
	},
	{
		link: "https://amzn.to/2twL81y",
		cover: "https://images.bible.cloud/covers/110x170/QXOLLB.jpg",
		name: "Southern Conchucos Ancash Quechua 2002 Edition",
		bid: "QXOLLB",
	},
	{
		link: "http://amzn.to/2f3aY9G",
		cover: "https://images.bible.cloud/covers/110x170/RAITBL.jpg",
		name: "Ramoaaina 2006 Edition",
		bid: "RAITBL",
	},
	{
		link: "http://amzn.to/2fli2LI",
		cover: "https://images.bible.cloud/covers/110x170/RKBWBT.jpg",
		name: "New Testament in Rikbaktsa",
		bid: "RKBWBT",
	},
	{
		link: "http://amzn.to/2eUz5DR",
		cover: "https://images.bible.cloud/covers/110x170/ROOWBT.jpg",
		name: "Rotokas 1982 Edition",
		bid: "ROOWBT",
	},
	{
		link: "http://amzn.to/2jum88W",
		cover: "https://images.bible.cloud/covers/110x170/RROPNG.jpg",
		name: "Waima 2002 Edition",
		bid: "RROPNG",
	},
	{
		link: "http://amzn.to/2jnir4K",
		cover: "https://images.bible.cloud/covers/110x170/RWOKAR.jpg",
		name: "Karo Rawa New Testament",
		bid: "RWOKAR",
	},
	{
		link: "http://amzn.to/2eUpKvK",
		cover: "https://images.bible.cloud/covers/110x170/SABWBT.jpg",
		name: "Buglere 2008 Edition",
		bid: "SABWBT",
	},
	{
		link: "http://amzn.to/2eUqjWd",
		cover: "https://images.bible.cloud/covers/110x170/SEHWBT.jpg",
		name: "The New Tesament in Sena",
		bid: "SEHWBT",
	},
	{
		link: "http://amzn.to/2y6bzvW",
		cover: "https://images.bible.cloud/covers/110x170/SEYWBT.jpg",
		name: "The New Testament in Secoya",
		bid: "SEYWBT",
	},
	{
		link: "http://amzn.to/2x4qick",
		cover: "https://images.bible.cloud/covers/110x170/SGBTBL.jpg",
		name: "Mag-antsi Ayta 2006 Edition",
		bid: "SGBTBL",
	},
	{
		link: "http://amzn.to/2fiR1Zl",
		cover: "https://images.bible.cloud/covers/110x170/SGZWBT.jpg",
		name: "Sursurunga 2009 Edition",
		bid: "SGZWBT",
	},
	{
		link: "https://amzn.to/2yK7r9n",
		cover: "https://images.bible.cloud/covers/110x170/SHPTBL.jpg",
		name: "Shipibo-Conibo 2012 Edition",
		bid: "SHPTBL",
	},
	{
		link: "http://amzn.to/2f5pbTh",
		cover: "https://images.bible.cloud/covers/110x170/SIMPNG.jpg",
		name: "Mende (Papua New Guinea) 2005 Edition",
		bid: "SIMPNG",
	},
	{
		link: "http://amzn.to/2fiIm9e",
		cover: "https://images.bible.cloud/covers/110x170/SJATBL.jpg",
		name: "Epena 2005 Edition",
		bid: "SJATBL",
	},
	{
		link: "http://amzn.to/2wdpu5Q",
		cover: "https://images.bible.cloud/covers/110x170/SLLTBL.jpg",
		name: "Salt-Yui 1978 Edition",
		bid: "SLLTBL",
	},
	{
		link: "http://amzn.to/2wXmha4",
		cover: "https://images.bible.cloud/covers/110x170/SMKWBT.jpg",
		name: "The New Testament in Bolinao",
		bid: "SMKWBT",
	},
	{
		link: "http://amzn.to/2jEKQDw",
		cover: "https://images.bible.cloud/covers/110x170/SNCPNG.jpg",
		name: "Sinaugoro 1995 Edition",
		bid: "SNCPNG",
	},
	{
		link: "http://amzn.to/2f608jj",
		cover: "https://images.bible.cloud/covers/110x170/SNNWBT.jpg",
		name: "The New Testament in Siona",
		bid: "SNNWBT",
	},
	{
		link: "http://amzn.to/2jqNahc",
		cover: "https://images.bible.cloud/covers/110x170/SNPSLV.jpg",
		name: "Siane 1997 Edition",
		bid: "SNPSLV",
	},
	{
		link: "http://amzn.to/2eYxb56",
		cover: "https://images.bible.cloud/covers/110x170/SNPWBT.jpg",
		name: "Komongu Siane New Testament",
		bid: "SNPWBT",
	},
	{
		link: "http://amzn.to/2eWcGpC",
		cover: "https://images.bible.cloud/covers/110x170/SOYSIM.jpg",
		name: "Miyobe 2011 Edition",
		bid: "SOYSIM",
	},
	{
		link: "http://amzn.to/2wcwwI0",
		cover: "https://images.bible.cloud/covers/110x170/SPLWBT.jpg",
		name: "Selepet 1986 Edition",
		bid: "SPLWBT",
	},
	{
		link: "http://amzn.to/2f8DHdl",
		cover: "https://images.bible.cloud/covers/110x170/SPPTBL.jpg",
		name: "Supyire Senoufo 2008 Edition",
		bid: "SPPTBL",
	},
	{
		link: "https://amzn.to/2yK5Nod",
		cover: "https://images.bible.cloud/covers/110x170/SPSWBT.jpg",
		name: "The New Testament in Saposa",
		bid: "SPSWBT",
	},
	{
		link: "http://amzn.to/2x4jDyJ",
		cover: "https://images.bible.cloud/covers/110x170/SPYWBT.jpg",
		name: "Sabaot 1997 Edition",
		bid: "SPYWBT",
	},
	{
		link: "http://amzn.to/2w8TMH7",
		cover: "https://images.bible.cloud/covers/110x170/SRMWBT.jpg",
		name: "Saramaccan 1998 Edition",
		bid: "SRMWBT",
	},
	{
		link: "http://amzn.to/2wa2uVy",
		cover: "https://images.bible.cloud/covers/110x170/SRNBSS.jpg",
		name: "Sranan Tongo 2002 Edition",
		bid: "SRNBSS",
	},
	{
		link: "https://amzn.to/2KjWmAp",
		cover: "https://images.bible.cloud/covers/110x170/SSDWBT.jpg",
		name: "Siroi 1999 Edition",
		bid: "SSDWBT",
	},
	{
		link: "http://amzn.to/2flBTud",
		cover: "https://images.bible.cloud/covers/110x170/SSGWBT.jpg",
		name: "Seimat 2012 Edition",
		bid: "SSGWBT",
	},
	{
		link: "https://amzn.to/2tyaH2r",
		cover: "https://images.bible.cloud/covers/110x170/STPTBL.jpg",
		name: "Southeastern Tepehuan 2007 Edition",
		bid: "STPTBL",
	},
	{
		link: "http://amzn.to/2wc64hP",
		cover: "https://images.bible.cloud/covers/110x170/SUEWBT.jpg",
		name: "Suena 2011 Edition",
		bid: "SUEWBT",
	},
	{
		link: "http://amzn.to/2jsRBIx",
		cover: "https://images.bible.cloud/covers/110x170/SXBWBT.jpg",
		name: "The New Testament in Suba",
		bid: "SXBWBT",
	},
	{
		link: "http://amzn.to/2x4IySL",
		cover: "https://images.bible.cloud/covers/110x170/TACPBC.jpg",
		name: "Lowland Tarahumara 2008 Edition",
		bid: "TACPBC",
	},
	{
		link: "https://amzn.to/2txkdTp",
		cover: "https://images.bible.cloud/covers/110x170/TAJWBT.jpg",
		name: "Eastern Tamang 2011 Edition",
		bid: "TAJWBT",
	},
	{
		link: "http://amzn.to/2x1KUSi",
		cover: "https://images.bible.cloud/covers/110x170/TAVWBT.jpg",
		name: "Tatuyo 2009 Edition",
		bid: "TAVWBT",
	},
	{
		link: "https://amzn.to/2KpV8Aa",
		cover: "https://images.bible.cloud/covers/110x170/TAWTNT.jpg",
		name: "Madang Province Tay New Testament",
		bid: "TAWTNT",
	},
	{
		link: "https://amzn.to/2MnwkcU",
		cover: "https://images.bible.cloud/covers/110x170/TBGWBT.jpg",
		name: "Tairora, North 2009 Edition",
		bid: "TBGWBT",
	},
	{
		link: "http://amzn.to/2jrP9St",
		cover: "https://images.bible.cloud/covers/110x170/TBOWBT.jpg",
		name: "Tawala 1985 Edition",
		bid: "TBOWBT",
	},
	{
		link: "http://amzn.to/2x4vvAO",
		cover: "https://images.bible.cloud/covers/110x170/TCATBL.jpg",
		name: "Ticuna 1986 Edition",
		bid: "TCATBL",
	},
	{
		link: "http://amzn.to/2xzyAdI",
		cover: "https://images.bible.cloud/covers/110x170/TERTBL.jpg",
		name: "Tereno 1994 Edition",
		bid: "TERTBL",
	},
	{
		link: "http://amzn.to/2xzskT5",
		cover: "https://images.bible.cloud/covers/110x170/TEWBDV.jpg",
		name: "Bible Portions in Tewa",
		bid: "TEWBDV",
	},
	{
		link: "http://amzn.to/2y6DnAh",
		cover: "https://images.bible.cloud/covers/110x170/TGPWBT.jpg",
		name: "The New Testament in Tangoa",
		bid: "TGPWBT",
	},
	{
		link: "https://amzn.to/2K8sVSt",
		cover: "https://images.bible.cloud/covers/110x170/TIMTBL.jpg",
		name: "The New Testament in Timbe",
		bid: "TIMTBL",
	},
	{
		link: "http://amzn.to/2w8ZhFE",
		cover: "https://images.bible.cloud/covers/110x170/TIYWBT.jpg",
		name: "The New Testament in Tiruray",
		bid: "TIYWBT",
	},
	{
		link: "https://amzn.to/2KcTtSD",
		cover: "https://images.bible.cloud/covers/110x170/TKUWBT.jpg",
		name: "New Testament in Totonac, Upper Necaxa",
		bid: "TKUWBT",
	},
	{
		link: "https://amzn.to/2N3TEgW",
		cover: "https://images.bible.cloud/covers/110x170/TLFWBT.jpg",
		name: "Telefol 1988 Edition",
		bid: "TLFWBT",
	},
	{
		link: "http://amzn.to/2jpEo2Y",
		cover: "https://images.bible.cloud/covers/110x170/TNAWBT.jpg",
		name: "The New Testament in Tacana (2009)",
		bid: "TNAWBT",
	},
	{
		link: "http://amzn.to/2y7knSn",
		cover: "https://images.bible.cloud/covers/110x170/TNCBLI.jpg",
		name: "New Testament Portions in Letuama",
		bid: "TNCBLI",
	},
	{
		link: "http://amzn.to/2x2kyjg",
		cover: "https://images.bible.cloud/covers/110x170/TNKWBT.jpg",
		name: "Kwamera 2013 Edition",
		bid: "TNKWBT",
	},
	{
		link: "https://amzn.to/2yMDvJC",
		cover: "https://images.bible.cloud/covers/110x170/TNNTNT.jpg",
		name: "The New Testament in Tanana, North",
		bid: "TNNTNT",
	},
	{
		link: "https://amzn.to/2yGTSYg",
		cover: "https://images.bible.cloud/covers/110x170/TNPTNP.jpg",
		name: "Whitesands New Testament",
		bid: "TNPTNP",
	},
	{
		link: "http://amzn.to/2xzero7",
		cover: "https://images.bible.cloud/covers/110x170/TOCTBL.jpg",
		name: "Coyutla Totonac 2006 Edition",
		bid: "TOCTBL",
	},
	{
		link: "https://amzn.to/2Kk0eRX",
		cover: "https://images.bible.cloud/covers/110x170/TODPBT.jpg",
		name: "God's Book in Toma",
		bid: "TODPBT",
	},
	{
		link: "http://amzn.to/2h47ZdY",
		cover: "https://images.bible.cloud/covers/110x170/TOJWBT.jpg",
		name: "The New Testament in Tojolabal",
		bid: "TOJWBT",
	},
	{
		link: "http://amzn.to/2y6rUkh",
		cover: "https://images.bible.cloud/covers/110x170/TOOWBT.jpg",
		name: "Xicotepec de Juárez Totonac Bible",
		bid: "TOOWBT",
	},
	{
		link: "https://amzn.to/2tEkwv6",
		cover: "https://images.bible.cloud/covers/110x170/TOPWBT.jpg",
		name: "New Testament in Totonaco de Papantla",
		bid: "TOPWBT",
	},
	{
		link: "https://amzn.to/2MpOScx",
		cover: "https://images.bible.cloud/covers/110x170/TOSTBL.jpg",
		name: "Highland Totonac 1999 Edition",
		bid: "TOSTBL",
	},
	{
		link: "http://amzn.to/2wqMMjU",
		cover: "https://images.bible.cloud/covers/110x170/TPTTBL.jpg",
		name: "Tlachichilco Tepehua 2004 Edition",
		bid: "TPTTBL",
	},
	{
		link: "http://amzn.to/2f5TMjY",
		cover: "https://images.bible.cloud/covers/110x170/TPZWBT.jpg",
		name: "Tinputz 2005 Edition",
		bid: "TPZWBT",
	},
	{
		link: "https://amzn.to/2yJqFvw",
		cover: "https://images.bible.cloud/covers/110x170/TRCWBT.jpg",
		name: "The New Testament in Copala Triqui",
		bid: "TRCWBT",
	},
	{
		link: "http://amzn.to/2h3rnYF",
		cover: "https://images.bible.cloud/covers/110x170/TSWWBT.jpg",
		name: "New Testament in Tsishingini",
		bid: "TSWWBT",
	},
	{
		link: "http://amzn.to/2wqGEZ6",
		cover: "https://images.bible.cloud/covers/110x170/TTCWBT.jpg",
		name: "Tektiteko 2003 Edition",
		bid: "TTCWBT",
	},
	{
		link: "https://amzn.to/2txBRq2",
		cover: "https://images.bible.cloud/covers/110x170/TTETBL.jpg",
		name: "Tubetube (Bwanabwana) New Testament",
		bid: "TTETBL",
	},
	{
		link: "http://amzn.to/2x2xXrk",
		cover: "https://images.bible.cloud/covers/110x170/TUCSNT.jpg",
		name: "Oov Saveeng New Testament and Portions",
		bid: "TUCSNT",
	},
	{
		link: "https://amzn.to/2tCCvTx",
		cover: "https://images.bible.cloud/covers/110x170/TUEWBT.jpg",
		name: "Tuyuca 2004 Edition",
		bid: "TUEWBT",
	},
	{
		link: "http://amzn.to/2wqsgjD",
		cover: "https://images.bible.cloud/covers/110x170/TUFWYI.jpg",
		name: "Central Tunebo 1987 Edition",
		bid: "TUFWYI",
	},
	{
		link: "http://amzn.to/2wq1at0",
		cover: "https://images.bible.cloud/covers/110x170/TXUTBL.jpg",
		name: "Kayapὀ 1996 Edition",
		bid: "TXUTBL",
	},
	{
		link: "http://amzn.to/2xzqtO7",
		cover: "https://images.bible.cloud/covers/110x170/TZJEAS.jpg",
		name: "New Testament in Tz'utujil Eastern",
		bid: "TZJEAS",
	},
	{
		link: "http://amzn.to/2x2glMl",
		cover: "https://images.bible.cloud/covers/110x170/TZJWES.jpg",
		name: "Tz'utujil 1992 Edition",
		bid: "TZJWES",
	},
	{
		link: "http://amzn.to/2h41NCE",
		cover: "https://images.bible.cloud/covers/110x170/TZOSAN.jpg",
		name: "New Testament in Tzotzil San Andres",
		bid: "TZOSAN",
	},
	{
		link: "http://amzn.to/2wq2V9A",
		cover: "https://images.bible.cloud/covers/110x170/TZOZIN.jpg",
		name: "New Testament in Tzotzil Zinacantan",
		bid: "TZOZIN",
	},
	{
		link: "https://amzn.to/2MZIny1",
		cover: "https://images.bible.cloud/covers/110x170/UBRTBL.jpg",
		name: "Ubir New Testament and Genesis",
		bid: "UBRTBL",
	},
	{
		link: "https://amzn.to/2KjF862",
		cover: "https://images.bible.cloud/covers/110x170/UBUNPG.jpg",
		name: "No Penge Umbu-Ungu New Testament",
		bid: "UBUNPG",
	},
	{
		link: "http://amzn.to/2xzdYCl",
		cover: "https://images.bible.cloud/covers/110x170/URBWBT.jpg",
		name: "The New Testament in Kaapor",
		bid: "URBWBT",
	},
	{
		link: "https://amzn.to/2tyRVb6",
		cover: "https://images.bible.cloud/covers/110x170/USAWBT.jpg",
		name: "New Testament in Usarufa",
		bid: "USAWBT",
	},
	{
		link: "http://amzn.to/2h4A2d4",
		cover: "https://images.bible.cloud/covers/110x170/USPWBT.jpg",
		name: "Uspanteco 1999 Edition",
		bid: "USPWBT",
	},

	{
		link: "https://amzn.to/2Kinb87",
		cover: "https://images.bible.cloud/covers/110x170/UVLUVL.jpg",
		name: "The New Testament in Lote",
		bid: "UVLUVL",
	},
	{
		link: "http://amzn.to/2joKD7h",
		cover: "https://images.bible.cloud/covers/110x170/VIVWBT.jpg",
		name: "Iduna 2003 Edition",
		bid: "VIVWBT",
	},
	{
		link: "http://amzn.to/2h3H7e2",
		cover: "https://images.bible.cloud/covers/110x170/VMYTBL.jpg",
		name: "Ayautla Mazatec 2009 Edition",
		bid: "VMYTBL",
	},
	{
		link: "https://amzn.to/2Ka8fti",
		cover: "https://images.bible.cloud/covers/110x170/WAJWBT.jpg",
		name: "Waffa 1975 Edition",
		bid: "WAJWBT",
	},
	{
		link: "http://amzn.to/2wqJI7x",
		cover: "https://images.bible.cloud/covers/110x170/WAPWBT.jpg",
		name: "Wapishana 2012 Edition",
		bid: "WAPWBT",
	},
	{
		link: "http://amzn.to/2wqdol7",
		cover: "https://images.bible.cloud/covers/110x170/WERWBT.jpg",
		name: "Weri 1984 Edition",
		bid: "WERWBT",
	},
	{
		link: "http://amzn.to/2xznYvf",
		cover: "https://images.bible.cloud/covers/110x170/WIUTBL.jpg",
		name: "New Testament in Witu",
		bid: "WIUTBL",
	},
	{
		link: "http://amzn.to/2xz0u9v",
		cover: "https://images.bible.cloud/covers/110x170/WMWWYI.jpg",
		name: "Mwani WBT Version",
		bid: "WMWWYI",
	},
	{
		link: "http://amzn.to/2wC3jBP",
		cover: "https://images.bible.cloud/covers/110x170/WNUPNG.jpg",
		name: "Usan 2001 Edition",
		bid: "WNUPNG",
	},
	{
		link: "https://amzn.to/2MrlNgO",
		cover: "https://images.bible.cloud/covers/110x170/WOSWBT.jpg",
		name: "Hanga Hundi 1997 Edition",
		bid: "WOSWBT",
	},
	{
		link: "http://amzn.to/2xhnvMP",
		cover: "https://images.bible.cloud/covers/110x170/WRSPNG.jpg",
		name: "New Testament in Waris",
		bid: "WRSPNG",
	},
	{
		link: "http://amzn.to/2jqpf1p",
		cover: "https://images.bible.cloud/covers/110x170/WUVWBT.jpg",
		name: "Wuvulu-Aua 2004 Edition",
		bid: "WUVWBT",
	},
	{
		link: "https://amzn.to/2KcTp5l",
		cover: "https://images.bible.cloud/covers/110x170/XAVTBL.jpg",
		name: "The New Testament in Xavante",
		bid: "XAVTBL",
	},
	{
		link: "http://amzn.to/2xz0M06",
		cover: "https://images.bible.cloud/covers/110x170/XBIYAN.jpg",
		name: "Kombio Yanimoi Bible Portions (2002)",
		bid: "XBIYAN",
	},
	{
		link: "https://amzn.to/2N0esG3",
		cover: "https://images.bible.cloud/covers/110x170/XEDWYI.jpg",
		name: "Hdi 2013 Edition",
		bid: "XEDWYI",
	},
	{
		link: "http://amzn.to/2hdCXk5",
		cover: "https://images.bible.cloud/covers/110x170/XLAPNG.jpg",
		name: "Kamula 2005 Edition",
		bid: "XLAPNG",
	},
	{
		link: "https://amzn.to/2MZQ7Qs",
		cover: "https://images.bible.cloud/covers/110x170/XONWBT.jpg",
		name: "Konkomba Likpakpaaln 1998 Edition",
		bid: "XONWBT",
	},
	{
		link: "http://amzn.to/2jrKRe2",
		cover: "https://images.bible.cloud/covers/110x170/XTDTBL.jpg",
		name: "Diuxi-Tilantongo Mixtec 2001 Edition",
		bid: "XTDTBL",
	},
	{
		link: "http://amzn.to/2jqGgbS",
		cover: "https://images.bible.cloud/covers/110x170/XTMWBT.jpg",
		name: "New Testament in Mixtec, Magdalena Peñasco",
		bid: "XTMWBT",
	},
	{
		link: "http://amzn.to/2xziMHT",
		cover: "https://images.bible.cloud/covers/110x170/YADTBL.jpg",
		name: "The New Testament in Yagua",
		bid: "YADTBL",
	},
	{
		link: "https://amzn.to/2KjZZX3",
		cover: "https://images.bible.cloud/covers/110x170/YALPBT.jpg",
		name: "Yalunka 2008 Edition",
		bid: "YALPBT",
	},
	{
		link: "http://amzn.to/2wqxziP",
		cover: "https://images.bible.cloud/covers/110x170/YAQTBL.jpg",
		name: "Yaqui New Testament (2003)",
		bid: "YAQTBL",
	},
	{
		link: "http://amzn.to/2w9UkfN",
		cover: "https://images.bible.cloud/covers/110x170/YCNWBT.jpg",
		name: "Yucuna WBT Version",
		bid: "YCNWBT",
	},
	{
		link: "https://amzn.to/2Ka9c4O",
		cover: "https://images.bible.cloud/covers/110x170/YKAWBT.jpg",
		name: "Yakan New Testament and Portions",
		bid: "YKAWBT",
	},
	{
		link: "http://amzn.to/2wpZAr2",
		cover: "https://images.bible.cloud/covers/110x170/YLETBL.jpg",
		name: "Rossel (Yele) New Testament",
		bid: "YLETBL",
	},
	{
		link: "http://amzn.to/2wqoDdw",
		cover: "https://images.bible.cloud/covers/110x170/YSSWBT.jpg",
		name: "The New Testament in Yessan-Mayo Yamano",
		bid: "YSSWBT",
	},
	{
		link: "http://amzn.to/2wre1uU",
		cover: "https://images.bible.cloud/covers/110x170/YUJWBT.jpg",
		name: "The New Testament in Karkar-Yuri",
		bid: "YUJWBT",
	},
	{
		link: "http://amzn.to/2wC9nud",
		cover: "https://images.bible.cloud/covers/110x170/YUWPNG.jpg",
		name: "Yau (Morobe Province) 1997 Edition",
		bid: "YUWPNG",
	},
	{
		link: "https://amzn.to/2ttGSQK",
		cover: "https://images.bible.cloud/covers/110x170/YVATBL.jpg",
		name: "Yawa 2011 Edition",
		bid: "YVATBL",
	},
	{
		link: "http://amzn.to/2xxRamg",
		cover: "https://images.bible.cloud/covers/110x170/ZAATBL.jpg",
		name: "Sierra de Juarez Zapotec 1970 Edition",
		bid: "ZAATBL",
	},
	{
		link: "http://amzn.to/2xz2b6R",
		cover: "https://images.bible.cloud/covers/110x170/ZABTBL.jpg",
		name: "San Juan Guelavia Zapotec 1995 Edition",
		bid: "ZABTBL",
	},
	{
		link: "http://amzn.to/2xz2HSl",
		cover: "https://images.bible.cloud/covers/110x170/ZACSIM.jpg",
		name: "Ocotlan Zapotec 1983 Edition",
		bid: "ZACSIM",
	},
	{
		link: "http://amzn.to/2xxSQw4",
		cover: "https://images.bible.cloud/covers/110x170/ZADWBT.jpg",
		name: "The New Testament in Cajonos Zapotec",
		bid: "ZADWBT",
	},
	{
		link: "http://amzn.to/2y6RmGe",
		cover: "https://images.bible.cloud/covers/110x170/ZAITBL.jpg",
		name: "Isthmus Zapotec 1988 Edition",
		bid: "ZAITBL",
	},
	{
		link: "http://amzn.to/2jo4YJX",
		cover: "https://images.bible.cloud/covers/110x170/ZAMILM.jpg",
		name: "Miahuatlan Zapotec 1971 Edition",
		bid: "ZAMILM",
	},
	{
		link: "http://amzn.to/2fjcAsx",
		cover: "https://images.bible.cloud/covers/110x170/ZAOTBL.jpg",
		name: "Ozolotepec Zapotec 2007 Edition",
		bid: "ZAOTBL",
	},
	{
		link: "http://amzn.to/2y6RUfg",
		cover: "https://images.bible.cloud/covers/110x170/ZARTBL.jpg",
		name: "Rincon Zapotec 1971 Edition",
		bid: "ZARTBL",
	},
	{
		link: "http://amzn.to/2f6T7yC",
		cover: "https://images.bible.cloud/covers/110x170/ZASWYI.jpg",
		name: "Santo Domingo Albarradas Zapotec 2010 Edition",
		bid: "ZASWYI",
	},
	{
		link: "http://amzn.to/2h34B2Q",
		cover: "https://images.bible.cloud/covers/110x170/ZAVTBL.jpg",
		name: "Zapoteco de Yatzachi New Testament",
		bid: "ZAVTBL",
	},
	{
		link: "http://amzn.to/2y8plye",
		cover: "https://images.bible.cloud/covers/110x170/ZAWMVR.jpg",
		name: "Mitla Zapotec 2006 Edition",
		bid: "ZAWMVR",
	},
	{
		link: "http://amzn.to/2x2i3xq",
		cover: "https://images.bible.cloud/covers/110x170/ZCAWBT.jpg",
		name: "Coatecas Altas Zapotec WBT Version",
		bid: "ZCAWBT",
	},
	{
		link: "http://amzn.to/2wab46x",
		cover: "https://images.bible.cloud/covers/110x170/ZIAWBT.jpg",
		name: "The New Testament in Zia",
		bid: "ZIAWBT",
	},
	{
		link: "http://amzn.to/2eXtJHY",
		cover: "https://images.bible.cloud/covers/110x170/ZOSTBL.jpg",
		name: "Francisco Leon Zoque 1984 Edition",
		bid: "ZOSTBL",
	},
	{
		link: "http://amzn.to/2w9aQwy",
		cover: "https://images.bible.cloud/covers/110x170/ZPCTBL.jpg",
		name: "Zapoteco del Choapan New Testament",
		bid: "ZPCTBL",
	},
	{
		link: "http://amzn.to/2w9C2v6",
		cover: "https://images.bible.cloud/covers/110x170/ZPIWYI.jpg",
		name: "Santa Mari­a Quiegolani Zapotec 2010 Edition",
		bid: "ZPIWYI",
	},
	{
		link: "http://amzn.to/2x2bLxz",
		cover: "https://images.bible.cloud/covers/110x170/ZPLTBL.jpg",
		name: "The New Testament in Lachixi­o Zapotec",
		bid: "ZPLTBL",
	},
	{
		link: "http://amzn.to/2fjvAaw",
		cover: "https://images.bible.cloud/covers/110x170/ZPOTBL.jpg",
		name: "The New Testament in Amatlan Zapotec",
		bid: "ZPOTBL",
	},
	{
		link: "http://amzn.to/2h34F2A",
		cover: "https://images.bible.cloud/covers/110x170/ZPQTBL.jpg",
		name: "The New Testament in Zoogocho Zapotec",
		bid: "ZPQTBL",
	},
	{
		link: "http://amzn.to/2x2nOLs",
		cover: "https://images.bible.cloud/covers/110x170/ZPUTBL.jpg",
		name: "Yalalag Zapotec 2000 Edition",
		bid: "ZPUTBL",
	},
	{
		link: "http://amzn.to/2wXONZc",
		cover: "https://images.bible.cloud/covers/110x170/ZPVTBL.jpg",
		name: "Zapoteco de Chichicapan New Testament",
		bid: "ZPVTBL",
	},
	{
		link: "https://amzn.to/2tEocgc",
		cover: "https://images.bible.cloud/covers/110x170/ZPZTBL.jpg",
		name: "Texmelucan Zapotec 2004 Edition",
		bid: "ZPZTBL",
	},
	{
		link: "http://amzn.to/2wqoIOa",
		cover: "https://images.bible.cloud/covers/110x170/ZSRWBT.jpg",
		name: "Zapoteco del Rincón Sur New Testament",
		bid: "ZSRWBT",
	},
	{
		link: "http://amzn.to/2wqtwTK",
		cover: "https://images.bible.cloud/covers/110x170/ZTQTBL.jpg",
		name: "Quioquitani-Quierí­ Zapotec 2000 Edition",
		bid: "ZTQTBL",
	},
	{
		link: "http://amzn.to/2wqJFbR",
		cover: "https://images.bible.cloud/covers/110x170/ZYPWBT.jpg",
		name: "New Testament in Chin, Zyphe",
		bid: "ZYPWBT",
	},
]

let query = ""
let results = [...printbibles]
let engine = new Fuse(printbibles, {
	shouldSort: true,
	includeMatches: true,
	threshold: 0.3, // At what point does the match algorithm give up. A threshold of 0.0 requires a perfect match (of both letters and location), a threshold of 1.0 would match anything.
	location: 0, // Determines approximately where in the text is the pattern expected to be found
	distance: 50, // Determines how close the match must be to the fuzzy location (specified by location). An exact letter match which is distance characters away from the fuzzy location would score as a complete mismatch. A distance of 0 requires the match be at the exact location specified. A distance of 1000 would require a perfect match to be within 800 characters of the location to be found using a threshold of 0.8
	maxPatternLength: 12,
	minMatchCharLength: 1,
	keys: ["name", "bid"],
})
let filter = function () {
	if (query == "") {
		results = printbibles
	} else {
		results = engine.search(query).slice(0, 100)
	}
}
</script>

<svelte:head>
	<title>
		{$t("common.Print on Demand")}
		{$t("common.Bibles")} | {$t("common.org_title")}
	</title>
</svelte:head>

<Banner
		title={$t("common.Print on Demand")}
		subtitle=""
		caption={$t("bible.bible_print_caption")}
		breadcrumbs={[
			{ link: `/bibles`, title: $t('common.Bibles') },
			{ link: '#', title: $t('common.Print on Demand') },
		]}
		subnav={[
		]} />

<section id="container" class="mx-auto max-w-5xl">

	<input
		type="search"
		placeholder="{$t('bible.bible_print_filter')}..."
		bind:value="{query}"
		on:input="{filter}"
		autocomplete
		class="mx-auto  my-8 block w-1/3 rounded-md bg-[url('/img/icons/filter.png')] bg-[length:15px_15px] bg-[top_8px_right_8px] bg-no-repeat py-1.5 px-2
			text-sm leading-5 text-gray-700 placeholder-gray-400 shadow-sm focus:border-gray-600
			focus:placeholder-gray-400 focus:outline-none focus:ring-1 focus:ring-gray-600 dark:bg-gray-300" />

	<div class="grid grid-cols-2 gap-6 md:grid-cols-4 md:gap-4">
		{#each results as print}
			<a
				href="{print.link ?? print.item.link}"
				class="flex rounded border border-gray-300 bg-white text-blue-700 shadow-xl hover:text-blue-600 dark:border-black
											dark:bg-gray-800 dark:text-white dark:hover:text-blue-800"
				target="_blank"
				rel="noopener noreferrer">
				<img src="{print.cover ?? print.item.cover}" alt="Cover" class="m-2 w-14" />
				<div class="relative m-2">
					<h3 class="w-full text-gray-800 dark:text-gray-100">
						{print.name ?? print.item.name}
					</h3>
					<h4
						class="absolute bottom-0 right-0 text-right text-xs leading-snug text-gray-600 dark:text-gray-300">
						{print.bid ?? print.item.bid}
					</h4>
				</div>
			</a>
		{/each}
	</div>
</section>
